// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Block.proto

package io.eigenphi.erigon.protos;

/**
 * Protobuf type {@code erigon.TraceTransaction}
 */
public final class TraceTransaction extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:erigon.TraceTransaction)
    TraceTransactionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TraceTransaction.newBuilder() to construct.
  private TraceTransaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TraceTransaction() {
    transactionHash_ = "";
    fromAddress_ = "";
    toAddress_ = "";
    input_ = "";
    transactionValue_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TraceTransaction();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TraceTransaction(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            blockNumber_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            transactionHash_ = s;
            break;
          }
          case 24: {

            transactionIndex_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            fromAddress_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            toAddress_ = s;
            break;
          }
          case 48: {

            gasPrice_ = input.readInt64();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            input_ = s;
            break;
          }
          case 64: {

            nonce_ = input.readInt64();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            transactionValue_ = s;
            break;
          }
          case 82: {
            io.eigenphi.erigon.protos.stackFrame.Builder subBuilder = null;
            if (stack_ != null) {
              subBuilder = stack_.toBuilder();
            }
            stack_ = input.readMessage(io.eigenphi.erigon.protos.stackFrame.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(stack_);
              stack_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_TraceTransaction_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_TraceTransaction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.eigenphi.erigon.protos.TraceTransaction.class, io.eigenphi.erigon.protos.TraceTransaction.Builder.class);
  }

  public static final int BLOCKNUMBER_FIELD_NUMBER = 1;
  private long blockNumber_;
  /**
   * <code>int64 blockNumber = 1;</code>
   * @return The blockNumber.
   */
  @java.lang.Override
  public long getBlockNumber() {
    return blockNumber_;
  }

  public static final int TRANSACTIONHASH_FIELD_NUMBER = 2;
  private volatile java.lang.Object transactionHash_;
  /**
   * <code>string transactionHash = 2;</code>
   * @return The transactionHash.
   */
  @java.lang.Override
  public java.lang.String getTransactionHash() {
    java.lang.Object ref = transactionHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transactionHash_ = s;
      return s;
    }
  }
  /**
   * <code>string transactionHash = 2;</code>
   * @return The bytes for transactionHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransactionHashBytes() {
    java.lang.Object ref = transactionHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transactionHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTIONINDEX_FIELD_NUMBER = 3;
  private int transactionIndex_;
  /**
   * <code>int32 transactionIndex = 3;</code>
   * @return The transactionIndex.
   */
  @java.lang.Override
  public int getTransactionIndex() {
    return transactionIndex_;
  }

  public static final int FROMADDRESS_FIELD_NUMBER = 4;
  private volatile java.lang.Object fromAddress_;
  /**
   * <code>string fromAddress = 4;</code>
   * @return The fromAddress.
   */
  @java.lang.Override
  public java.lang.String getFromAddress() {
    java.lang.Object ref = fromAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string fromAddress = 4;</code>
   * @return The bytes for fromAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromAddressBytes() {
    java.lang.Object ref = fromAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOADDRESS_FIELD_NUMBER = 5;
  private volatile java.lang.Object toAddress_;
  /**
   * <code>string toAddress = 5;</code>
   * @return The toAddress.
   */
  @java.lang.Override
  public java.lang.String getToAddress() {
    java.lang.Object ref = toAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string toAddress = 5;</code>
   * @return The bytes for toAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToAddressBytes() {
    java.lang.Object ref = toAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GASPRICE_FIELD_NUMBER = 6;
  private long gasPrice_;
  /**
   * <code>int64 gasPrice = 6;</code>
   * @return The gasPrice.
   */
  @java.lang.Override
  public long getGasPrice() {
    return gasPrice_;
  }

  public static final int INPUT_FIELD_NUMBER = 7;
  private volatile java.lang.Object input_;
  /**
   * <code>string input = 7;</code>
   * @return The input.
   */
  @java.lang.Override
  public java.lang.String getInput() {
    java.lang.Object ref = input_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      input_ = s;
      return s;
    }
  }
  /**
   * <code>string input = 7;</code>
   * @return The bytes for input.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInputBytes() {
    java.lang.Object ref = input_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      input_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NONCE_FIELD_NUMBER = 8;
  private long nonce_;
  /**
   * <code>int64 nonce = 8;</code>
   * @return The nonce.
   */
  @java.lang.Override
  public long getNonce() {
    return nonce_;
  }

  public static final int TRANSACTIONVALUE_FIELD_NUMBER = 9;
  private volatile java.lang.Object transactionValue_;
  /**
   * <code>string transactionValue = 9;</code>
   * @return The transactionValue.
   */
  @java.lang.Override
  public java.lang.String getTransactionValue() {
    java.lang.Object ref = transactionValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transactionValue_ = s;
      return s;
    }
  }
  /**
   * <code>string transactionValue = 9;</code>
   * @return The bytes for transactionValue.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransactionValueBytes() {
    java.lang.Object ref = transactionValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transactionValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STACK_FIELD_NUMBER = 10;
  private io.eigenphi.erigon.protos.stackFrame stack_;
  /**
   * <code>.erigon.stackFrame stack = 10;</code>
   * @return Whether the stack field is set.
   */
  @java.lang.Override
  public boolean hasStack() {
    return stack_ != null;
  }
  /**
   * <code>.erigon.stackFrame stack = 10;</code>
   * @return The stack.
   */
  @java.lang.Override
  public io.eigenphi.erigon.protos.stackFrame getStack() {
    return stack_ == null ? io.eigenphi.erigon.protos.stackFrame.getDefaultInstance() : stack_;
  }
  /**
   * <code>.erigon.stackFrame stack = 10;</code>
   */
  @java.lang.Override
  public io.eigenphi.erigon.protos.stackFrameOrBuilder getStackOrBuilder() {
    return getStack();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (blockNumber_ != 0L) {
      output.writeInt64(1, blockNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionHash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, transactionHash_);
    }
    if (transactionIndex_ != 0) {
      output.writeInt32(3, transactionIndex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromAddress_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromAddress_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toAddress_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, toAddress_);
    }
    if (gasPrice_ != 0L) {
      output.writeInt64(6, gasPrice_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(input_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, input_);
    }
    if (nonce_ != 0L) {
      output.writeInt64(8, nonce_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionValue_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, transactionValue_);
    }
    if (stack_ != null) {
      output.writeMessage(10, getStack());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (blockNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, blockNumber_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionHash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, transactionHash_);
    }
    if (transactionIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, transactionIndex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromAddress_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromAddress_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toAddress_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, toAddress_);
    }
    if (gasPrice_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, gasPrice_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(input_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, input_);
    }
    if (nonce_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, nonce_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionValue_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, transactionValue_);
    }
    if (stack_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getStack());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.eigenphi.erigon.protos.TraceTransaction)) {
      return super.equals(obj);
    }
    io.eigenphi.erigon.protos.TraceTransaction other = (io.eigenphi.erigon.protos.TraceTransaction) obj;

    if (getBlockNumber()
        != other.getBlockNumber()) return false;
    if (!getTransactionHash()
        .equals(other.getTransactionHash())) return false;
    if (getTransactionIndex()
        != other.getTransactionIndex()) return false;
    if (!getFromAddress()
        .equals(other.getFromAddress())) return false;
    if (!getToAddress()
        .equals(other.getToAddress())) return false;
    if (getGasPrice()
        != other.getGasPrice()) return false;
    if (!getInput()
        .equals(other.getInput())) return false;
    if (getNonce()
        != other.getNonce()) return false;
    if (!getTransactionValue()
        .equals(other.getTransactionValue())) return false;
    if (hasStack() != other.hasStack()) return false;
    if (hasStack()) {
      if (!getStack()
          .equals(other.getStack())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BLOCKNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlockNumber());
    hash = (37 * hash) + TRANSACTIONHASH_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionHash().hashCode();
    hash = (37 * hash) + TRANSACTIONINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionIndex();
    hash = (37 * hash) + FROMADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getFromAddress().hashCode();
    hash = (37 * hash) + TOADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getToAddress().hashCode();
    hash = (37 * hash) + GASPRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGasPrice());
    hash = (37 * hash) + INPUT_FIELD_NUMBER;
    hash = (53 * hash) + getInput().hashCode();
    hash = (37 * hash) + NONCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNonce());
    hash = (37 * hash) + TRANSACTIONVALUE_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionValue().hashCode();
    if (hasStack()) {
      hash = (37 * hash) + STACK_FIELD_NUMBER;
      hash = (53 * hash) + getStack().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.eigenphi.erigon.protos.TraceTransaction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.eigenphi.erigon.protos.TraceTransaction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.TraceTransaction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.eigenphi.erigon.protos.TraceTransaction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.TraceTransaction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.eigenphi.erigon.protos.TraceTransaction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.TraceTransaction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.eigenphi.erigon.protos.TraceTransaction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.TraceTransaction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.eigenphi.erigon.protos.TraceTransaction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.TraceTransaction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.eigenphi.erigon.protos.TraceTransaction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.eigenphi.erigon.protos.TraceTransaction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code erigon.TraceTransaction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:erigon.TraceTransaction)
      io.eigenphi.erigon.protos.TraceTransactionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_TraceTransaction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_TraceTransaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.eigenphi.erigon.protos.TraceTransaction.class, io.eigenphi.erigon.protos.TraceTransaction.Builder.class);
    }

    // Construct using io.eigenphi.erigon.protos.TraceTransaction.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      blockNumber_ = 0L;

      transactionHash_ = "";

      transactionIndex_ = 0;

      fromAddress_ = "";

      toAddress_ = "";

      gasPrice_ = 0L;

      input_ = "";

      nonce_ = 0L;

      transactionValue_ = "";

      if (stackBuilder_ == null) {
        stack_ = null;
      } else {
        stack_ = null;
        stackBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_TraceTransaction_descriptor;
    }

    @java.lang.Override
    public io.eigenphi.erigon.protos.TraceTransaction getDefaultInstanceForType() {
      return io.eigenphi.erigon.protos.TraceTransaction.getDefaultInstance();
    }

    @java.lang.Override
    public io.eigenphi.erigon.protos.TraceTransaction build() {
      io.eigenphi.erigon.protos.TraceTransaction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.eigenphi.erigon.protos.TraceTransaction buildPartial() {
      io.eigenphi.erigon.protos.TraceTransaction result = new io.eigenphi.erigon.protos.TraceTransaction(this);
      result.blockNumber_ = blockNumber_;
      result.transactionHash_ = transactionHash_;
      result.transactionIndex_ = transactionIndex_;
      result.fromAddress_ = fromAddress_;
      result.toAddress_ = toAddress_;
      result.gasPrice_ = gasPrice_;
      result.input_ = input_;
      result.nonce_ = nonce_;
      result.transactionValue_ = transactionValue_;
      if (stackBuilder_ == null) {
        result.stack_ = stack_;
      } else {
        result.stack_ = stackBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.eigenphi.erigon.protos.TraceTransaction) {
        return mergeFrom((io.eigenphi.erigon.protos.TraceTransaction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.eigenphi.erigon.protos.TraceTransaction other) {
      if (other == io.eigenphi.erigon.protos.TraceTransaction.getDefaultInstance()) return this;
      if (other.getBlockNumber() != 0L) {
        setBlockNumber(other.getBlockNumber());
      }
      if (!other.getTransactionHash().isEmpty()) {
        transactionHash_ = other.transactionHash_;
        onChanged();
      }
      if (other.getTransactionIndex() != 0) {
        setTransactionIndex(other.getTransactionIndex());
      }
      if (!other.getFromAddress().isEmpty()) {
        fromAddress_ = other.fromAddress_;
        onChanged();
      }
      if (!other.getToAddress().isEmpty()) {
        toAddress_ = other.toAddress_;
        onChanged();
      }
      if (other.getGasPrice() != 0L) {
        setGasPrice(other.getGasPrice());
      }
      if (!other.getInput().isEmpty()) {
        input_ = other.input_;
        onChanged();
      }
      if (other.getNonce() != 0L) {
        setNonce(other.getNonce());
      }
      if (!other.getTransactionValue().isEmpty()) {
        transactionValue_ = other.transactionValue_;
        onChanged();
      }
      if (other.hasStack()) {
        mergeStack(other.getStack());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.eigenphi.erigon.protos.TraceTransaction parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.eigenphi.erigon.protos.TraceTransaction) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long blockNumber_ ;
    /**
     * <code>int64 blockNumber = 1;</code>
     * @return The blockNumber.
     */
    @java.lang.Override
    public long getBlockNumber() {
      return blockNumber_;
    }
    /**
     * <code>int64 blockNumber = 1;</code>
     * @param value The blockNumber to set.
     * @return This builder for chaining.
     */
    public Builder setBlockNumber(long value) {
      
      blockNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 blockNumber = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockNumber() {
      
      blockNumber_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object transactionHash_ = "";
    /**
     * <code>string transactionHash = 2;</code>
     * @return The transactionHash.
     */
    public java.lang.String getTransactionHash() {
      java.lang.Object ref = transactionHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transactionHash = 2;</code>
     * @return The bytes for transactionHash.
     */
    public com.google.protobuf.ByteString
        getTransactionHashBytes() {
      java.lang.Object ref = transactionHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transactionHash = 2;</code>
     * @param value The transactionHash to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transactionHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transactionHash = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionHash() {
      
      transactionHash_ = getDefaultInstance().getTransactionHash();
      onChanged();
      return this;
    }
    /**
     * <code>string transactionHash = 2;</code>
     * @param value The bytes for transactionHash to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transactionHash_ = value;
      onChanged();
      return this;
    }

    private int transactionIndex_ ;
    /**
     * <code>int32 transactionIndex = 3;</code>
     * @return The transactionIndex.
     */
    @java.lang.Override
    public int getTransactionIndex() {
      return transactionIndex_;
    }
    /**
     * <code>int32 transactionIndex = 3;</code>
     * @param value The transactionIndex to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionIndex(int value) {
      
      transactionIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 transactionIndex = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionIndex() {
      
      transactionIndex_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object fromAddress_ = "";
    /**
     * <code>string fromAddress = 4;</code>
     * @return The fromAddress.
     */
    public java.lang.String getFromAddress() {
      java.lang.Object ref = fromAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fromAddress = 4;</code>
     * @return The bytes for fromAddress.
     */
    public com.google.protobuf.ByteString
        getFromAddressBytes() {
      java.lang.Object ref = fromAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fromAddress = 4;</code>
     * @param value The fromAddress to set.
     * @return This builder for chaining.
     */
    public Builder setFromAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fromAddress = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromAddress() {
      
      fromAddress_ = getDefaultInstance().getFromAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string fromAddress = 4;</code>
     * @param value The bytes for fromAddress to set.
     * @return This builder for chaining.
     */
    public Builder setFromAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromAddress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object toAddress_ = "";
    /**
     * <code>string toAddress = 5;</code>
     * @return The toAddress.
     */
    public java.lang.String getToAddress() {
      java.lang.Object ref = toAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string toAddress = 5;</code>
     * @return The bytes for toAddress.
     */
    public com.google.protobuf.ByteString
        getToAddressBytes() {
      java.lang.Object ref = toAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string toAddress = 5;</code>
     * @param value The toAddress to set.
     * @return This builder for chaining.
     */
    public Builder setToAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      toAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string toAddress = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearToAddress() {
      
      toAddress_ = getDefaultInstance().getToAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string toAddress = 5;</code>
     * @param value The bytes for toAddress to set.
     * @return This builder for chaining.
     */
    public Builder setToAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      toAddress_ = value;
      onChanged();
      return this;
    }

    private long gasPrice_ ;
    /**
     * <code>int64 gasPrice = 6;</code>
     * @return The gasPrice.
     */
    @java.lang.Override
    public long getGasPrice() {
      return gasPrice_;
    }
    /**
     * <code>int64 gasPrice = 6;</code>
     * @param value The gasPrice to set.
     * @return This builder for chaining.
     */
    public Builder setGasPrice(long value) {
      
      gasPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 gasPrice = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearGasPrice() {
      
      gasPrice_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object input_ = "";
    /**
     * <code>string input = 7;</code>
     * @return The input.
     */
    public java.lang.String getInput() {
      java.lang.Object ref = input_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        input_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string input = 7;</code>
     * @return The bytes for input.
     */
    public com.google.protobuf.ByteString
        getInputBytes() {
      java.lang.Object ref = input_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        input_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string input = 7;</code>
     * @param value The input to set.
     * @return This builder for chaining.
     */
    public Builder setInput(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      input_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string input = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearInput() {
      
      input_ = getDefaultInstance().getInput();
      onChanged();
      return this;
    }
    /**
     * <code>string input = 7;</code>
     * @param value The bytes for input to set.
     * @return This builder for chaining.
     */
    public Builder setInputBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      input_ = value;
      onChanged();
      return this;
    }

    private long nonce_ ;
    /**
     * <code>int64 nonce = 8;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public long getNonce() {
      return nonce_;
    }
    /**
     * <code>int64 nonce = 8;</code>
     * @param value The nonce to set.
     * @return This builder for chaining.
     */
    public Builder setNonce(long value) {
      
      nonce_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 nonce = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonce() {
      
      nonce_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object transactionValue_ = "";
    /**
     * <code>string transactionValue = 9;</code>
     * @return The transactionValue.
     */
    public java.lang.String getTransactionValue() {
      java.lang.Object ref = transactionValue_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transactionValue = 9;</code>
     * @return The bytes for transactionValue.
     */
    public com.google.protobuf.ByteString
        getTransactionValueBytes() {
      java.lang.Object ref = transactionValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transactionValue = 9;</code>
     * @param value The transactionValue to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transactionValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transactionValue = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionValue() {
      
      transactionValue_ = getDefaultInstance().getTransactionValue();
      onChanged();
      return this;
    }
    /**
     * <code>string transactionValue = 9;</code>
     * @param value The bytes for transactionValue to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transactionValue_ = value;
      onChanged();
      return this;
    }

    private io.eigenphi.erigon.protos.stackFrame stack_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.eigenphi.erigon.protos.stackFrame, io.eigenphi.erigon.protos.stackFrame.Builder, io.eigenphi.erigon.protos.stackFrameOrBuilder> stackBuilder_;
    /**
     * <code>.erigon.stackFrame stack = 10;</code>
     * @return Whether the stack field is set.
     */
    public boolean hasStack() {
      return stackBuilder_ != null || stack_ != null;
    }
    /**
     * <code>.erigon.stackFrame stack = 10;</code>
     * @return The stack.
     */
    public io.eigenphi.erigon.protos.stackFrame getStack() {
      if (stackBuilder_ == null) {
        return stack_ == null ? io.eigenphi.erigon.protos.stackFrame.getDefaultInstance() : stack_;
      } else {
        return stackBuilder_.getMessage();
      }
    }
    /**
     * <code>.erigon.stackFrame stack = 10;</code>
     */
    public Builder setStack(io.eigenphi.erigon.protos.stackFrame value) {
      if (stackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stack_ = value;
        onChanged();
      } else {
        stackBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.erigon.stackFrame stack = 10;</code>
     */
    public Builder setStack(
        io.eigenphi.erigon.protos.stackFrame.Builder builderForValue) {
      if (stackBuilder_ == null) {
        stack_ = builderForValue.build();
        onChanged();
      } else {
        stackBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.erigon.stackFrame stack = 10;</code>
     */
    public Builder mergeStack(io.eigenphi.erigon.protos.stackFrame value) {
      if (stackBuilder_ == null) {
        if (stack_ != null) {
          stack_ =
            io.eigenphi.erigon.protos.stackFrame.newBuilder(stack_).mergeFrom(value).buildPartial();
        } else {
          stack_ = value;
        }
        onChanged();
      } else {
        stackBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.erigon.stackFrame stack = 10;</code>
     */
    public Builder clearStack() {
      if (stackBuilder_ == null) {
        stack_ = null;
        onChanged();
      } else {
        stack_ = null;
        stackBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.erigon.stackFrame stack = 10;</code>
     */
    public io.eigenphi.erigon.protos.stackFrame.Builder getStackBuilder() {
      
      onChanged();
      return getStackFieldBuilder().getBuilder();
    }
    /**
     * <code>.erigon.stackFrame stack = 10;</code>
     */
    public io.eigenphi.erigon.protos.stackFrameOrBuilder getStackOrBuilder() {
      if (stackBuilder_ != null) {
        return stackBuilder_.getMessageOrBuilder();
      } else {
        return stack_ == null ?
            io.eigenphi.erigon.protos.stackFrame.getDefaultInstance() : stack_;
      }
    }
    /**
     * <code>.erigon.stackFrame stack = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.eigenphi.erigon.protos.stackFrame, io.eigenphi.erigon.protos.stackFrame.Builder, io.eigenphi.erigon.protos.stackFrameOrBuilder> 
        getStackFieldBuilder() {
      if (stackBuilder_ == null) {
        stackBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.eigenphi.erigon.protos.stackFrame, io.eigenphi.erigon.protos.stackFrame.Builder, io.eigenphi.erigon.protos.stackFrameOrBuilder>(
                getStack(),
                getParentForChildren(),
                isClean());
        stack_ = null;
      }
      return stackBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:erigon.TraceTransaction)
  }

  // @@protoc_insertion_point(class_scope:erigon.TraceTransaction)
  private static final io.eigenphi.erigon.protos.TraceTransaction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.eigenphi.erigon.protos.TraceTransaction();
  }

  public static io.eigenphi.erigon.protos.TraceTransaction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TraceTransaction>
      PARSER = new com.google.protobuf.AbstractParser<TraceTransaction>() {
    @java.lang.Override
    public TraceTransaction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TraceTransaction(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TraceTransaction> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TraceTransaction> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.eigenphi.erigon.protos.TraceTransaction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

