// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Block.proto

package io.eigenphi.erigon.protos;

public interface BlockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:erigon.Block)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 blockNumber = 2;</code>
   * @return The blockNumber.
   */
  long getBlockNumber();

  /**
   * <code>string blockHash = 3;</code>
   * @return The blockHash.
   */
  java.lang.String getBlockHash();
  /**
   * <code>string blockHash = 3;</code>
   * @return The bytes for blockHash.
   */
  com.google.protobuf.ByteString
      getBlockHashBytes();

  /**
   * <code>string parentHash = 4;</code>
   * @return The parentHash.
   */
  java.lang.String getParentHash();
  /**
   * <code>string parentHash = 4;</code>
   * @return The bytes for parentHash.
   */
  com.google.protobuf.ByteString
      getParentHashBytes();

  /**
   * <code>string miner = 6;</code>
   * @return The miner.
   */
  java.lang.String getMiner();
  /**
   * <code>string miner = 6;</code>
   * @return The bytes for miner.
   */
  com.google.protobuf.ByteString
      getMinerBytes();

  /**
   * <code>int32 blockSize = 7;</code>
   * @return The blockSize.
   */
  int getBlockSize();

  /**
   * <code>int64 gasLimit = 8;</code>
   * @return The gasLimit.
   */
  long getGasLimit();

  /**
   * <code>int64 gasUsed = 9;</code>
   * @return The gasUsed.
   */
  long getGasUsed();

  /**
   * <code>int64 blockTimestamp = 10;</code>
   * @return The blockTimestamp.
   */
  long getBlockTimestamp();
}
