// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Block.proto

package io.eigenphi.erigon.protos;

/**
 * Protobuf type {@code erigon.EventLog}
 */
public final class EventLog extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:erigon.EventLog)
    EventLogOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EventLog.newBuilder() to construct.
  private EventLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EventLog() {
    chain_ = "";
    address_ = "";
    topic0_ = "";
    topic1_ = "";
    topic2_ = "";
    topic3_ = "";
    data_ = "";
    transactionHash_ = "";
    blockHash_ = "";
    senderInfo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EventLog();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_EventLog_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_EventLog_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.eigenphi.erigon.protos.EventLog.class, io.eigenphi.erigon.protos.EventLog.Builder.class);
  }

  public static final int CHAIN_FIELD_NUMBER = 1;
  private volatile java.lang.Object chain_;
  /**
   * <code>string chain = 1;</code>
   * @return The chain.
   */
  @java.lang.Override
  public java.lang.String getChain() {
    java.lang.Object ref = chain_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chain_ = s;
      return s;
    }
  }
  /**
   * <code>string chain = 1;</code>
   * @return The bytes for chain.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChainBytes() {
    java.lang.Object ref = chain_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chain_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ADDRESS_FIELD_NUMBER = 2;
  private volatile java.lang.Object address_;
  /**
   * <code>string address = 2;</code>
   * @return The address.
   */
  @java.lang.Override
  public java.lang.String getAddress() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      address_ = s;
      return s;
    }
  }
  /**
   * <code>string address = 2;</code>
   * @return The bytes for address.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddressBytes() {
    java.lang.Object ref = address_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      address_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPIC0_FIELD_NUMBER = 3;
  private volatile java.lang.Object topic0_;
  /**
   * <code>string topic0 = 3;</code>
   * @return The topic0.
   */
  @java.lang.Override
  public java.lang.String getTopic0() {
    java.lang.Object ref = topic0_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic0_ = s;
      return s;
    }
  }
  /**
   * <code>string topic0 = 3;</code>
   * @return The bytes for topic0.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTopic0Bytes() {
    java.lang.Object ref = topic0_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic0_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPIC1_FIELD_NUMBER = 4;
  private volatile java.lang.Object topic1_;
  /**
   * <code>string topic1 = 4;</code>
   * @return The topic1.
   */
  @java.lang.Override
  public java.lang.String getTopic1() {
    java.lang.Object ref = topic1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic1_ = s;
      return s;
    }
  }
  /**
   * <code>string topic1 = 4;</code>
   * @return The bytes for topic1.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTopic1Bytes() {
    java.lang.Object ref = topic1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPIC2_FIELD_NUMBER = 5;
  private volatile java.lang.Object topic2_;
  /**
   * <code>string topic2 = 5;</code>
   * @return The topic2.
   */
  @java.lang.Override
  public java.lang.String getTopic2() {
    java.lang.Object ref = topic2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic2_ = s;
      return s;
    }
  }
  /**
   * <code>string topic2 = 5;</code>
   * @return The bytes for topic2.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTopic2Bytes() {
    java.lang.Object ref = topic2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPIC3_FIELD_NUMBER = 6;
  private volatile java.lang.Object topic3_;
  /**
   * <code>string topic3 = 6;</code>
   * @return The topic3.
   */
  @java.lang.Override
  public java.lang.String getTopic3() {
    java.lang.Object ref = topic3_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic3_ = s;
      return s;
    }
  }
  /**
   * <code>string topic3 = 6;</code>
   * @return The bytes for topic3.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTopic3Bytes() {
    java.lang.Object ref = topic3_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 7;
  private volatile java.lang.Object data_;
  /**
   * <code>string data = 7;</code>
   * @return The data.
   */
  @java.lang.Override
  public java.lang.String getData() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      data_ = s;
      return s;
    }
  }
  /**
   * <code>string data = 7;</code>
   * @return The bytes for data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataBytes() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLOCKNUMBER_FIELD_NUMBER = 8;
  private long blockNumber_;
  /**
   * <code>int64 blockNumber = 8;</code>
   * @return The blockNumber.
   */
  @java.lang.Override
  public long getBlockNumber() {
    return blockNumber_;
  }

  public static final int BLOCKTIMESTAMP_FIELD_NUMBER = 9;
  private long blockTimestamp_;
  /**
   * <code>int64 blockTimestamp = 9;</code>
   * @return The blockTimestamp.
   */
  @java.lang.Override
  public long getBlockTimestamp() {
    return blockTimestamp_;
  }

  public static final int TRANSACTIONHASH_FIELD_NUMBER = 10;
  private volatile java.lang.Object transactionHash_;
  /**
   * <code>string transactionHash = 10;</code>
   * @return The transactionHash.
   */
  @java.lang.Override
  public java.lang.String getTransactionHash() {
    java.lang.Object ref = transactionHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transactionHash_ = s;
      return s;
    }
  }
  /**
   * <code>string transactionHash = 10;</code>
   * @return The bytes for transactionHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransactionHashBytes() {
    java.lang.Object ref = transactionHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transactionHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTIONINDEX_FIELD_NUMBER = 11;
  private int transactionIndex_;
  /**
   * <code>int32 transactionIndex = 11;</code>
   * @return The transactionIndex.
   */
  @java.lang.Override
  public int getTransactionIndex() {
    return transactionIndex_;
  }

  public static final int BLOCKHASH_FIELD_NUMBER = 12;
  private volatile java.lang.Object blockHash_;
  /**
   * <code>string blockHash = 12;</code>
   * @return The blockHash.
   */
  @java.lang.Override
  public java.lang.String getBlockHash() {
    java.lang.Object ref = blockHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      blockHash_ = s;
      return s;
    }
  }
  /**
   * <code>string blockHash = 12;</code>
   * @return The bytes for blockHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBlockHashBytes() {
    java.lang.Object ref = blockHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      blockHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGINDEX_FIELD_NUMBER = 13;
  private int logIndex_;
  /**
   * <code>int32 logIndex = 13;</code>
   * @return The logIndex.
   */
  @java.lang.Override
  public int getLogIndex() {
    return logIndex_;
  }

  public static final int REMOVED_FIELD_NUMBER = 14;
  private boolean removed_;
  /**
   * <code>bool removed = 14;</code>
   * @return The removed.
   */
  @java.lang.Override
  public boolean getRemoved() {
    return removed_;
  }

  public static final int SENDERINFO_FIELD_NUMBER = 15;
  private volatile java.lang.Object senderInfo_;
  /**
   * <code>string senderInfo = 15;</code>
   * @return The senderInfo.
   */
  @java.lang.Override
  public java.lang.String getSenderInfo() {
    java.lang.Object ref = senderInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string senderInfo = 15;</code>
   * @return The bytes for senderInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderInfoBytes() {
    java.lang.Object ref = senderInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chain_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chain_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, address_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic0_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, topic0_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic1_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, topic1_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic2_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, topic2_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic3_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, topic3_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, data_);
    }
    if (blockNumber_ != 0L) {
      output.writeInt64(8, blockNumber_);
    }
    if (blockTimestamp_ != 0L) {
      output.writeInt64(9, blockTimestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionHash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, transactionHash_);
    }
    if (transactionIndex_ != 0) {
      output.writeInt32(11, transactionIndex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockHash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, blockHash_);
    }
    if (logIndex_ != 0) {
      output.writeInt32(13, logIndex_);
    }
    if (removed_ != false) {
      output.writeBool(14, removed_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderInfo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, senderInfo_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chain_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chain_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(address_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, address_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic0_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, topic0_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic1_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, topic1_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic2_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, topic2_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(topic3_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, topic3_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, data_);
    }
    if (blockNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, blockNumber_);
    }
    if (blockTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, blockTimestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionHash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, transactionHash_);
    }
    if (transactionIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, transactionIndex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockHash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, blockHash_);
    }
    if (logIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, logIndex_);
    }
    if (removed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, removed_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderInfo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, senderInfo_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.eigenphi.erigon.protos.EventLog)) {
      return super.equals(obj);
    }
    io.eigenphi.erigon.protos.EventLog other = (io.eigenphi.erigon.protos.EventLog) obj;

    if (!getChain()
        .equals(other.getChain())) return false;
    if (!getAddress()
        .equals(other.getAddress())) return false;
    if (!getTopic0()
        .equals(other.getTopic0())) return false;
    if (!getTopic1()
        .equals(other.getTopic1())) return false;
    if (!getTopic2()
        .equals(other.getTopic2())) return false;
    if (!getTopic3()
        .equals(other.getTopic3())) return false;
    if (!getData()
        .equals(other.getData())) return false;
    if (getBlockNumber()
        != other.getBlockNumber()) return false;
    if (getBlockTimestamp()
        != other.getBlockTimestamp()) return false;
    if (!getTransactionHash()
        .equals(other.getTransactionHash())) return false;
    if (getTransactionIndex()
        != other.getTransactionIndex()) return false;
    if (!getBlockHash()
        .equals(other.getBlockHash())) return false;
    if (getLogIndex()
        != other.getLogIndex()) return false;
    if (getRemoved()
        != other.getRemoved()) return false;
    if (!getSenderInfo()
        .equals(other.getSenderInfo())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHAIN_FIELD_NUMBER;
    hash = (53 * hash) + getChain().hashCode();
    hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getAddress().hashCode();
    hash = (37 * hash) + TOPIC0_FIELD_NUMBER;
    hash = (53 * hash) + getTopic0().hashCode();
    hash = (37 * hash) + TOPIC1_FIELD_NUMBER;
    hash = (53 * hash) + getTopic1().hashCode();
    hash = (37 * hash) + TOPIC2_FIELD_NUMBER;
    hash = (53 * hash) + getTopic2().hashCode();
    hash = (37 * hash) + TOPIC3_FIELD_NUMBER;
    hash = (53 * hash) + getTopic3().hashCode();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + BLOCKNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlockNumber());
    hash = (37 * hash) + BLOCKTIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlockTimestamp());
    hash = (37 * hash) + TRANSACTIONHASH_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionHash().hashCode();
    hash = (37 * hash) + TRANSACTIONINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionIndex();
    hash = (37 * hash) + BLOCKHASH_FIELD_NUMBER;
    hash = (53 * hash) + getBlockHash().hashCode();
    hash = (37 * hash) + LOGINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getLogIndex();
    hash = (37 * hash) + REMOVED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRemoved());
    hash = (37 * hash) + SENDERINFO_FIELD_NUMBER;
    hash = (53 * hash) + getSenderInfo().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.eigenphi.erigon.protos.EventLog parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.eigenphi.erigon.protos.EventLog parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.EventLog parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.eigenphi.erigon.protos.EventLog parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.EventLog parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.eigenphi.erigon.protos.EventLog parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.EventLog parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.eigenphi.erigon.protos.EventLog parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.EventLog parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.eigenphi.erigon.protos.EventLog parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.EventLog parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.eigenphi.erigon.protos.EventLog parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.eigenphi.erigon.protos.EventLog prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code erigon.EventLog}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:erigon.EventLog)
      io.eigenphi.erigon.protos.EventLogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_EventLog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_EventLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.eigenphi.erigon.protos.EventLog.class, io.eigenphi.erigon.protos.EventLog.Builder.class);
    }

    // Construct using io.eigenphi.erigon.protos.EventLog.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      chain_ = "";

      address_ = "";

      topic0_ = "";

      topic1_ = "";

      topic2_ = "";

      topic3_ = "";

      data_ = "";

      blockNumber_ = 0L;

      blockTimestamp_ = 0L;

      transactionHash_ = "";

      transactionIndex_ = 0;

      blockHash_ = "";

      logIndex_ = 0;

      removed_ = false;

      senderInfo_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_EventLog_descriptor;
    }

    @java.lang.Override
    public io.eigenphi.erigon.protos.EventLog getDefaultInstanceForType() {
      return io.eigenphi.erigon.protos.EventLog.getDefaultInstance();
    }

    @java.lang.Override
    public io.eigenphi.erigon.protos.EventLog build() {
      io.eigenphi.erigon.protos.EventLog result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.eigenphi.erigon.protos.EventLog buildPartial() {
      io.eigenphi.erigon.protos.EventLog result = new io.eigenphi.erigon.protos.EventLog(this);
      result.chain_ = chain_;
      result.address_ = address_;
      result.topic0_ = topic0_;
      result.topic1_ = topic1_;
      result.topic2_ = topic2_;
      result.topic3_ = topic3_;
      result.data_ = data_;
      result.blockNumber_ = blockNumber_;
      result.blockTimestamp_ = blockTimestamp_;
      result.transactionHash_ = transactionHash_;
      result.transactionIndex_ = transactionIndex_;
      result.blockHash_ = blockHash_;
      result.logIndex_ = logIndex_;
      result.removed_ = removed_;
      result.senderInfo_ = senderInfo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.eigenphi.erigon.protos.EventLog) {
        return mergeFrom((io.eigenphi.erigon.protos.EventLog)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.eigenphi.erigon.protos.EventLog other) {
      if (other == io.eigenphi.erigon.protos.EventLog.getDefaultInstance()) return this;
      if (!other.getChain().isEmpty()) {
        chain_ = other.chain_;
        onChanged();
      }
      if (!other.getAddress().isEmpty()) {
        address_ = other.address_;
        onChanged();
      }
      if (!other.getTopic0().isEmpty()) {
        topic0_ = other.topic0_;
        onChanged();
      }
      if (!other.getTopic1().isEmpty()) {
        topic1_ = other.topic1_;
        onChanged();
      }
      if (!other.getTopic2().isEmpty()) {
        topic2_ = other.topic2_;
        onChanged();
      }
      if (!other.getTopic3().isEmpty()) {
        topic3_ = other.topic3_;
        onChanged();
      }
      if (!other.getData().isEmpty()) {
        data_ = other.data_;
        onChanged();
      }
      if (other.getBlockNumber() != 0L) {
        setBlockNumber(other.getBlockNumber());
      }
      if (other.getBlockTimestamp() != 0L) {
        setBlockTimestamp(other.getBlockTimestamp());
      }
      if (!other.getTransactionHash().isEmpty()) {
        transactionHash_ = other.transactionHash_;
        onChanged();
      }
      if (other.getTransactionIndex() != 0) {
        setTransactionIndex(other.getTransactionIndex());
      }
      if (!other.getBlockHash().isEmpty()) {
        blockHash_ = other.blockHash_;
        onChanged();
      }
      if (other.getLogIndex() != 0) {
        setLogIndex(other.getLogIndex());
      }
      if (other.getRemoved() != false) {
        setRemoved(other.getRemoved());
      }
      if (!other.getSenderInfo().isEmpty()) {
        senderInfo_ = other.senderInfo_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              chain_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              address_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              topic0_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              topic1_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              topic2_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              topic3_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 58: {
              data_ = input.readStringRequireUtf8();

              break;
            } // case 58
            case 64: {
              blockNumber_ = input.readInt64();

              break;
            } // case 64
            case 72: {
              blockTimestamp_ = input.readInt64();

              break;
            } // case 72
            case 82: {
              transactionHash_ = input.readStringRequireUtf8();

              break;
            } // case 82
            case 88: {
              transactionIndex_ = input.readInt32();

              break;
            } // case 88
            case 98: {
              blockHash_ = input.readStringRequireUtf8();

              break;
            } // case 98
            case 104: {
              logIndex_ = input.readInt32();

              break;
            } // case 104
            case 112: {
              removed_ = input.readBool();

              break;
            } // case 112
            case 122: {
              senderInfo_ = input.readStringRequireUtf8();

              break;
            } // case 122
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object chain_ = "";
    /**
     * <code>string chain = 1;</code>
     * @return The chain.
     */
    public java.lang.String getChain() {
      java.lang.Object ref = chain_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chain_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string chain = 1;</code>
     * @return The bytes for chain.
     */
    public com.google.protobuf.ByteString
        getChainBytes() {
      java.lang.Object ref = chain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string chain = 1;</code>
     * @param value The chain to set.
     * @return This builder for chaining.
     */
    public Builder setChain(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chain_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string chain = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChain() {
      
      chain_ = getDefaultInstance().getChain();
      onChanged();
      return this;
    }
    /**
     * <code>string chain = 1;</code>
     * @param value The bytes for chain to set.
     * @return This builder for chaining.
     */
    public Builder setChainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chain_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object address_ = "";
    /**
     * <code>string address = 2;</code>
     * @return The address.
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string address = 2;</code>
     * @return The bytes for address.
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string address = 2;</code>
     * @param value The address to set.
     * @return This builder for chaining.
     */
    public Builder setAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      address_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string address = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddress() {
      
      address_ = getDefaultInstance().getAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string address = 2;</code>
     * @param value The bytes for address to set.
     * @return This builder for chaining.
     */
    public Builder setAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      address_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object topic0_ = "";
    /**
     * <code>string topic0 = 3;</code>
     * @return The topic0.
     */
    public java.lang.String getTopic0() {
      java.lang.Object ref = topic0_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic0_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topic0 = 3;</code>
     * @return The bytes for topic0.
     */
    public com.google.protobuf.ByteString
        getTopic0Bytes() {
      java.lang.Object ref = topic0_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic0_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topic0 = 3;</code>
     * @param value The topic0 to set.
     * @return This builder for chaining.
     */
    public Builder setTopic0(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic0_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topic0 = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic0() {
      
      topic0_ = getDefaultInstance().getTopic0();
      onChanged();
      return this;
    }
    /**
     * <code>string topic0 = 3;</code>
     * @param value The bytes for topic0 to set.
     * @return This builder for chaining.
     */
    public Builder setTopic0Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic0_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object topic1_ = "";
    /**
     * <code>string topic1 = 4;</code>
     * @return The topic1.
     */
    public java.lang.String getTopic1() {
      java.lang.Object ref = topic1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topic1 = 4;</code>
     * @return The bytes for topic1.
     */
    public com.google.protobuf.ByteString
        getTopic1Bytes() {
      java.lang.Object ref = topic1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topic1 = 4;</code>
     * @param value The topic1 to set.
     * @return This builder for chaining.
     */
    public Builder setTopic1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topic1 = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic1() {
      
      topic1_ = getDefaultInstance().getTopic1();
      onChanged();
      return this;
    }
    /**
     * <code>string topic1 = 4;</code>
     * @param value The bytes for topic1 to set.
     * @return This builder for chaining.
     */
    public Builder setTopic1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic1_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object topic2_ = "";
    /**
     * <code>string topic2 = 5;</code>
     * @return The topic2.
     */
    public java.lang.String getTopic2() {
      java.lang.Object ref = topic2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topic2 = 5;</code>
     * @return The bytes for topic2.
     */
    public com.google.protobuf.ByteString
        getTopic2Bytes() {
      java.lang.Object ref = topic2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topic2 = 5;</code>
     * @param value The topic2 to set.
     * @return This builder for chaining.
     */
    public Builder setTopic2(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topic2 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic2() {
      
      topic2_ = getDefaultInstance().getTopic2();
      onChanged();
      return this;
    }
    /**
     * <code>string topic2 = 5;</code>
     * @param value The bytes for topic2 to set.
     * @return This builder for chaining.
     */
    public Builder setTopic2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic2_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object topic3_ = "";
    /**
     * <code>string topic3 = 6;</code>
     * @return The topic3.
     */
    public java.lang.String getTopic3() {
      java.lang.Object ref = topic3_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic3_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topic3 = 6;</code>
     * @return The bytes for topic3.
     */
    public com.google.protobuf.ByteString
        getTopic3Bytes() {
      java.lang.Object ref = topic3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topic3 = 6;</code>
     * @param value The topic3 to set.
     * @return This builder for chaining.
     */
    public Builder setTopic3(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topic3 = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic3() {
      
      topic3_ = getDefaultInstance().getTopic3();
      onChanged();
      return this;
    }
    /**
     * <code>string topic3 = 6;</code>
     * @param value The bytes for topic3 to set.
     * @return This builder for chaining.
     */
    public Builder setTopic3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic3_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object data_ = "";
    /**
     * <code>string data = 7;</code>
     * @return The data.
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string data = 7;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string data = 7;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string data = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }
    /**
     * <code>string data = 7;</code>
     * @param value The bytes for data to set.
     * @return This builder for chaining.
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      data_ = value;
      onChanged();
      return this;
    }

    private long blockNumber_ ;
    /**
     * <code>int64 blockNumber = 8;</code>
     * @return The blockNumber.
     */
    @java.lang.Override
    public long getBlockNumber() {
      return blockNumber_;
    }
    /**
     * <code>int64 blockNumber = 8;</code>
     * @param value The blockNumber to set.
     * @return This builder for chaining.
     */
    public Builder setBlockNumber(long value) {
      
      blockNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 blockNumber = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockNumber() {
      
      blockNumber_ = 0L;
      onChanged();
      return this;
    }

    private long blockTimestamp_ ;
    /**
     * <code>int64 blockTimestamp = 9;</code>
     * @return The blockTimestamp.
     */
    @java.lang.Override
    public long getBlockTimestamp() {
      return blockTimestamp_;
    }
    /**
     * <code>int64 blockTimestamp = 9;</code>
     * @param value The blockTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setBlockTimestamp(long value) {
      
      blockTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 blockTimestamp = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockTimestamp() {
      
      blockTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object transactionHash_ = "";
    /**
     * <code>string transactionHash = 10;</code>
     * @return The transactionHash.
     */
    public java.lang.String getTransactionHash() {
      java.lang.Object ref = transactionHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transactionHash = 10;</code>
     * @return The bytes for transactionHash.
     */
    public com.google.protobuf.ByteString
        getTransactionHashBytes() {
      java.lang.Object ref = transactionHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transactionHash = 10;</code>
     * @param value The transactionHash to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transactionHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transactionHash = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionHash() {
      
      transactionHash_ = getDefaultInstance().getTransactionHash();
      onChanged();
      return this;
    }
    /**
     * <code>string transactionHash = 10;</code>
     * @param value The bytes for transactionHash to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transactionHash_ = value;
      onChanged();
      return this;
    }

    private int transactionIndex_ ;
    /**
     * <code>int32 transactionIndex = 11;</code>
     * @return The transactionIndex.
     */
    @java.lang.Override
    public int getTransactionIndex() {
      return transactionIndex_;
    }
    /**
     * <code>int32 transactionIndex = 11;</code>
     * @param value The transactionIndex to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionIndex(int value) {
      
      transactionIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 transactionIndex = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionIndex() {
      
      transactionIndex_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object blockHash_ = "";
    /**
     * <code>string blockHash = 12;</code>
     * @return The blockHash.
     */
    public java.lang.String getBlockHash() {
      java.lang.Object ref = blockHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        blockHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string blockHash = 12;</code>
     * @return The bytes for blockHash.
     */
    public com.google.protobuf.ByteString
        getBlockHashBytes() {
      java.lang.Object ref = blockHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blockHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string blockHash = 12;</code>
     * @param value The blockHash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      blockHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string blockHash = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockHash() {
      
      blockHash_ = getDefaultInstance().getBlockHash();
      onChanged();
      return this;
    }
    /**
     * <code>string blockHash = 12;</code>
     * @param value The bytes for blockHash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      blockHash_ = value;
      onChanged();
      return this;
    }

    private int logIndex_ ;
    /**
     * <code>int32 logIndex = 13;</code>
     * @return The logIndex.
     */
    @java.lang.Override
    public int getLogIndex() {
      return logIndex_;
    }
    /**
     * <code>int32 logIndex = 13;</code>
     * @param value The logIndex to set.
     * @return This builder for chaining.
     */
    public Builder setLogIndex(int value) {
      
      logIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 logIndex = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogIndex() {
      
      logIndex_ = 0;
      onChanged();
      return this;
    }

    private boolean removed_ ;
    /**
     * <code>bool removed = 14;</code>
     * @return The removed.
     */
    @java.lang.Override
    public boolean getRemoved() {
      return removed_;
    }
    /**
     * <code>bool removed = 14;</code>
     * @param value The removed to set.
     * @return This builder for chaining.
     */
    public Builder setRemoved(boolean value) {
      
      removed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool removed = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemoved() {
      
      removed_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object senderInfo_ = "";
    /**
     * <code>string senderInfo = 15;</code>
     * @return The senderInfo.
     */
    public java.lang.String getSenderInfo() {
      java.lang.Object ref = senderInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string senderInfo = 15;</code>
     * @return The bytes for senderInfo.
     */
    public com.google.protobuf.ByteString
        getSenderInfoBytes() {
      java.lang.Object ref = senderInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string senderInfo = 15;</code>
     * @param value The senderInfo to set.
     * @return This builder for chaining.
     */
    public Builder setSenderInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string senderInfo = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderInfo() {
      
      senderInfo_ = getDefaultInstance().getSenderInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string senderInfo = 15;</code>
     * @param value The bytes for senderInfo to set.
     * @return This builder for chaining.
     */
    public Builder setSenderInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderInfo_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:erigon.EventLog)
  }

  // @@protoc_insertion_point(class_scope:erigon.EventLog)
  private static final io.eigenphi.erigon.protos.EventLog DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.eigenphi.erigon.protos.EventLog();
  }

  public static io.eigenphi.erigon.protos.EventLog getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EventLog>
      PARSER = new com.google.protobuf.AbstractParser<EventLog>() {
    @java.lang.Override
    public EventLog parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EventLog> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EventLog> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.eigenphi.erigon.protos.EventLog getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

