// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Block.proto

package io.eigenphi.erigon.protos;

/**
 * Protobuf type {@code erigon.Receipt}
 */
public final class Receipt extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:erigon.Receipt)
    ReceiptOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Receipt.newBuilder() to construct.
  private Receipt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Receipt() {
    chain_ = "";
    transactionHash_ = "";
    blockHash_ = "";
    contractAddress_ = "";
    eventLogs_ = java.util.Collections.emptyList();
    senderInfo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Receipt();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_Receipt_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_Receipt_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.eigenphi.erigon.protos.Receipt.class, io.eigenphi.erigon.protos.Receipt.Builder.class);
  }

  public static final int CHAIN_FIELD_NUMBER = 1;
  private volatile java.lang.Object chain_;
  /**
   * <code>string chain = 1;</code>
   * @return The chain.
   */
  @java.lang.Override
  public java.lang.String getChain() {
    java.lang.Object ref = chain_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chain_ = s;
      return s;
    }
  }
  /**
   * <code>string chain = 1;</code>
   * @return The bytes for chain.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChainBytes() {
    java.lang.Object ref = chain_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chain_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTIONHASH_FIELD_NUMBER = 2;
  private volatile java.lang.Object transactionHash_;
  /**
   * <code>string transactionHash = 2;</code>
   * @return The transactionHash.
   */
  @java.lang.Override
  public java.lang.String getTransactionHash() {
    java.lang.Object ref = transactionHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transactionHash_ = s;
      return s;
    }
  }
  /**
   * <code>string transactionHash = 2;</code>
   * @return The bytes for transactionHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransactionHashBytes() {
    java.lang.Object ref = transactionHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transactionHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTIONINDEX_FIELD_NUMBER = 3;
  private int transactionIndex_;
  /**
   * <code>int32 transactionIndex = 3;</code>
   * @return The transactionIndex.
   */
  @java.lang.Override
  public int getTransactionIndex() {
    return transactionIndex_;
  }

  public static final int BLOCKHASH_FIELD_NUMBER = 4;
  private volatile java.lang.Object blockHash_;
  /**
   * <code>string blockHash = 4;</code>
   * @return The blockHash.
   */
  @java.lang.Override
  public java.lang.String getBlockHash() {
    java.lang.Object ref = blockHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      blockHash_ = s;
      return s;
    }
  }
  /**
   * <code>string blockHash = 4;</code>
   * @return The bytes for blockHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBlockHashBytes() {
    java.lang.Object ref = blockHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      blockHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLOCKNUMBER_FIELD_NUMBER = 5;
  private long blockNumber_;
  /**
   * <code>int64 blockNumber = 5;</code>
   * @return The blockNumber.
   */
  @java.lang.Override
  public long getBlockNumber() {
    return blockNumber_;
  }

  public static final int GASUSED_FIELD_NUMBER = 6;
  private long gasUsed_;
  /**
   * <code>int64 gasUsed = 6;</code>
   * @return The gasUsed.
   */
  @java.lang.Override
  public long getGasUsed() {
    return gasUsed_;
  }

  public static final int CONTRACTADDRESS_FIELD_NUMBER = 7;
  private volatile java.lang.Object contractAddress_;
  /**
   * <code>string contractAddress = 7;</code>
   * @return The contractAddress.
   */
  @java.lang.Override
  public java.lang.String getContractAddress() {
    java.lang.Object ref = contractAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string contractAddress = 7;</code>
   * @return The bytes for contractAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContractAddressBytes() {
    java.lang.Object ref = contractAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTIONRECEIPTSTATUS_FIELD_NUMBER = 8;
  private boolean transactionReceiptStatus_;
  /**
   * <code>bool transactionReceiptStatus = 8;</code>
   * @return The transactionReceiptStatus.
   */
  @java.lang.Override
  public boolean getTransactionReceiptStatus() {
    return transactionReceiptStatus_;
  }

  public static final int EVENTCOUNT_FIELD_NUMBER = 9;
  private int eventCount_;
  /**
   * <code>int32 eventCount = 9;</code>
   * @return The eventCount.
   */
  @java.lang.Override
  public int getEventCount() {
    return eventCount_;
  }

  public static final int BLOCKTIMESTAMP_FIELD_NUMBER = 10;
  private long blockTimestamp_;
  /**
   * <code>int64 blockTimestamp = 10;</code>
   * @return The blockTimestamp.
   */
  @java.lang.Override
  public long getBlockTimestamp() {
    return blockTimestamp_;
  }

  public static final int EVENTLOGS_FIELD_NUMBER = 11;
  private java.util.List<io.eigenphi.erigon.protos.EventLog> eventLogs_;
  /**
   * <code>repeated .erigon.EventLog eventLogs = 11;</code>
   */
  @java.lang.Override
  public java.util.List<io.eigenphi.erigon.protos.EventLog> getEventLogsList() {
    return eventLogs_;
  }
  /**
   * <code>repeated .erigon.EventLog eventLogs = 11;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.eigenphi.erigon.protos.EventLogOrBuilder> 
      getEventLogsOrBuilderList() {
    return eventLogs_;
  }
  /**
   * <code>repeated .erigon.EventLog eventLogs = 11;</code>
   */
  @java.lang.Override
  public int getEventLogsCount() {
    return eventLogs_.size();
  }
  /**
   * <code>repeated .erigon.EventLog eventLogs = 11;</code>
   */
  @java.lang.Override
  public io.eigenphi.erigon.protos.EventLog getEventLogs(int index) {
    return eventLogs_.get(index);
  }
  /**
   * <code>repeated .erigon.EventLog eventLogs = 11;</code>
   */
  @java.lang.Override
  public io.eigenphi.erigon.protos.EventLogOrBuilder getEventLogsOrBuilder(
      int index) {
    return eventLogs_.get(index);
  }

  public static final int SENDERINFO_FIELD_NUMBER = 12;
  private volatile java.lang.Object senderInfo_;
  /**
   * <code>string senderInfo = 12;</code>
   * @return The senderInfo.
   */
  @java.lang.Override
  public java.lang.String getSenderInfo() {
    java.lang.Object ref = senderInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string senderInfo = 12;</code>
   * @return The bytes for senderInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderInfoBytes() {
    java.lang.Object ref = senderInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chain_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chain_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionHash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, transactionHash_);
    }
    if (transactionIndex_ != 0) {
      output.writeInt32(3, transactionIndex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockHash_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, blockHash_);
    }
    if (blockNumber_ != 0L) {
      output.writeInt64(5, blockNumber_);
    }
    if (gasUsed_ != 0L) {
      output.writeInt64(6, gasUsed_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractAddress_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, contractAddress_);
    }
    if (transactionReceiptStatus_ != false) {
      output.writeBool(8, transactionReceiptStatus_);
    }
    if (eventCount_ != 0) {
      output.writeInt32(9, eventCount_);
    }
    if (blockTimestamp_ != 0L) {
      output.writeInt64(10, blockTimestamp_);
    }
    for (int i = 0; i < eventLogs_.size(); i++) {
      output.writeMessage(11, eventLogs_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderInfo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, senderInfo_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chain_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chain_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionHash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, transactionHash_);
    }
    if (transactionIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, transactionIndex_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockHash_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, blockHash_);
    }
    if (blockNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, blockNumber_);
    }
    if (gasUsed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, gasUsed_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractAddress_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, contractAddress_);
    }
    if (transactionReceiptStatus_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, transactionReceiptStatus_);
    }
    if (eventCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, eventCount_);
    }
    if (blockTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, blockTimestamp_);
    }
    for (int i = 0; i < eventLogs_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, eventLogs_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderInfo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, senderInfo_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.eigenphi.erigon.protos.Receipt)) {
      return super.equals(obj);
    }
    io.eigenphi.erigon.protos.Receipt other = (io.eigenphi.erigon.protos.Receipt) obj;

    if (!getChain()
        .equals(other.getChain())) return false;
    if (!getTransactionHash()
        .equals(other.getTransactionHash())) return false;
    if (getTransactionIndex()
        != other.getTransactionIndex()) return false;
    if (!getBlockHash()
        .equals(other.getBlockHash())) return false;
    if (getBlockNumber()
        != other.getBlockNumber()) return false;
    if (getGasUsed()
        != other.getGasUsed()) return false;
    if (!getContractAddress()
        .equals(other.getContractAddress())) return false;
    if (getTransactionReceiptStatus()
        != other.getTransactionReceiptStatus()) return false;
    if (getEventCount()
        != other.getEventCount()) return false;
    if (getBlockTimestamp()
        != other.getBlockTimestamp()) return false;
    if (!getEventLogsList()
        .equals(other.getEventLogsList())) return false;
    if (!getSenderInfo()
        .equals(other.getSenderInfo())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHAIN_FIELD_NUMBER;
    hash = (53 * hash) + getChain().hashCode();
    hash = (37 * hash) + TRANSACTIONHASH_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionHash().hashCode();
    hash = (37 * hash) + TRANSACTIONINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionIndex();
    hash = (37 * hash) + BLOCKHASH_FIELD_NUMBER;
    hash = (53 * hash) + getBlockHash().hashCode();
    hash = (37 * hash) + BLOCKNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlockNumber());
    hash = (37 * hash) + GASUSED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGasUsed());
    hash = (37 * hash) + CONTRACTADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getContractAddress().hashCode();
    hash = (37 * hash) + TRANSACTIONRECEIPTSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTransactionReceiptStatus());
    hash = (37 * hash) + EVENTCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getEventCount();
    hash = (37 * hash) + BLOCKTIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBlockTimestamp());
    if (getEventLogsCount() > 0) {
      hash = (37 * hash) + EVENTLOGS_FIELD_NUMBER;
      hash = (53 * hash) + getEventLogsList().hashCode();
    }
    hash = (37 * hash) + SENDERINFO_FIELD_NUMBER;
    hash = (53 * hash) + getSenderInfo().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.eigenphi.erigon.protos.Receipt parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.eigenphi.erigon.protos.Receipt parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.Receipt parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.eigenphi.erigon.protos.Receipt parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.Receipt parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.eigenphi.erigon.protos.Receipt parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.Receipt parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.eigenphi.erigon.protos.Receipt parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.Receipt parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.eigenphi.erigon.protos.Receipt parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.Receipt parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.eigenphi.erigon.protos.Receipt parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.eigenphi.erigon.protos.Receipt prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code erigon.Receipt}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:erigon.Receipt)
      io.eigenphi.erigon.protos.ReceiptOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_Receipt_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_Receipt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.eigenphi.erigon.protos.Receipt.class, io.eigenphi.erigon.protos.Receipt.Builder.class);
    }

    // Construct using io.eigenphi.erigon.protos.Receipt.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      chain_ = "";

      transactionHash_ = "";

      transactionIndex_ = 0;

      blockHash_ = "";

      blockNumber_ = 0L;

      gasUsed_ = 0L;

      contractAddress_ = "";

      transactionReceiptStatus_ = false;

      eventCount_ = 0;

      blockTimestamp_ = 0L;

      if (eventLogsBuilder_ == null) {
        eventLogs_ = java.util.Collections.emptyList();
      } else {
        eventLogs_ = null;
        eventLogsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      senderInfo_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_Receipt_descriptor;
    }

    @java.lang.Override
    public io.eigenphi.erigon.protos.Receipt getDefaultInstanceForType() {
      return io.eigenphi.erigon.protos.Receipt.getDefaultInstance();
    }

    @java.lang.Override
    public io.eigenphi.erigon.protos.Receipt build() {
      io.eigenphi.erigon.protos.Receipt result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.eigenphi.erigon.protos.Receipt buildPartial() {
      io.eigenphi.erigon.protos.Receipt result = new io.eigenphi.erigon.protos.Receipt(this);
      int from_bitField0_ = bitField0_;
      result.chain_ = chain_;
      result.transactionHash_ = transactionHash_;
      result.transactionIndex_ = transactionIndex_;
      result.blockHash_ = blockHash_;
      result.blockNumber_ = blockNumber_;
      result.gasUsed_ = gasUsed_;
      result.contractAddress_ = contractAddress_;
      result.transactionReceiptStatus_ = transactionReceiptStatus_;
      result.eventCount_ = eventCount_;
      result.blockTimestamp_ = blockTimestamp_;
      if (eventLogsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          eventLogs_ = java.util.Collections.unmodifiableList(eventLogs_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.eventLogs_ = eventLogs_;
      } else {
        result.eventLogs_ = eventLogsBuilder_.build();
      }
      result.senderInfo_ = senderInfo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.eigenphi.erigon.protos.Receipt) {
        return mergeFrom((io.eigenphi.erigon.protos.Receipt)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.eigenphi.erigon.protos.Receipt other) {
      if (other == io.eigenphi.erigon.protos.Receipt.getDefaultInstance()) return this;
      if (!other.getChain().isEmpty()) {
        chain_ = other.chain_;
        onChanged();
      }
      if (!other.getTransactionHash().isEmpty()) {
        transactionHash_ = other.transactionHash_;
        onChanged();
      }
      if (other.getTransactionIndex() != 0) {
        setTransactionIndex(other.getTransactionIndex());
      }
      if (!other.getBlockHash().isEmpty()) {
        blockHash_ = other.blockHash_;
        onChanged();
      }
      if (other.getBlockNumber() != 0L) {
        setBlockNumber(other.getBlockNumber());
      }
      if (other.getGasUsed() != 0L) {
        setGasUsed(other.getGasUsed());
      }
      if (!other.getContractAddress().isEmpty()) {
        contractAddress_ = other.contractAddress_;
        onChanged();
      }
      if (other.getTransactionReceiptStatus() != false) {
        setTransactionReceiptStatus(other.getTransactionReceiptStatus());
      }
      if (other.getEventCount() != 0) {
        setEventCount(other.getEventCount());
      }
      if (other.getBlockTimestamp() != 0L) {
        setBlockTimestamp(other.getBlockTimestamp());
      }
      if (eventLogsBuilder_ == null) {
        if (!other.eventLogs_.isEmpty()) {
          if (eventLogs_.isEmpty()) {
            eventLogs_ = other.eventLogs_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEventLogsIsMutable();
            eventLogs_.addAll(other.eventLogs_);
          }
          onChanged();
        }
      } else {
        if (!other.eventLogs_.isEmpty()) {
          if (eventLogsBuilder_.isEmpty()) {
            eventLogsBuilder_.dispose();
            eventLogsBuilder_ = null;
            eventLogs_ = other.eventLogs_;
            bitField0_ = (bitField0_ & ~0x00000001);
            eventLogsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEventLogsFieldBuilder() : null;
          } else {
            eventLogsBuilder_.addAllMessages(other.eventLogs_);
          }
        }
      }
      if (!other.getSenderInfo().isEmpty()) {
        senderInfo_ = other.senderInfo_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              chain_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              transactionHash_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 24: {
              transactionIndex_ = input.readInt32();

              break;
            } // case 24
            case 34: {
              blockHash_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 40: {
              blockNumber_ = input.readInt64();

              break;
            } // case 40
            case 48: {
              gasUsed_ = input.readInt64();

              break;
            } // case 48
            case 58: {
              contractAddress_ = input.readStringRequireUtf8();

              break;
            } // case 58
            case 64: {
              transactionReceiptStatus_ = input.readBool();

              break;
            } // case 64
            case 72: {
              eventCount_ = input.readInt32();

              break;
            } // case 72
            case 80: {
              blockTimestamp_ = input.readInt64();

              break;
            } // case 80
            case 90: {
              io.eigenphi.erigon.protos.EventLog m =
                  input.readMessage(
                      io.eigenphi.erigon.protos.EventLog.parser(),
                      extensionRegistry);
              if (eventLogsBuilder_ == null) {
                ensureEventLogsIsMutable();
                eventLogs_.add(m);
              } else {
                eventLogsBuilder_.addMessage(m);
              }
              break;
            } // case 90
            case 98: {
              senderInfo_ = input.readStringRequireUtf8();

              break;
            } // case 98
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object chain_ = "";
    /**
     * <code>string chain = 1;</code>
     * @return The chain.
     */
    public java.lang.String getChain() {
      java.lang.Object ref = chain_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chain_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string chain = 1;</code>
     * @return The bytes for chain.
     */
    public com.google.protobuf.ByteString
        getChainBytes() {
      java.lang.Object ref = chain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string chain = 1;</code>
     * @param value The chain to set.
     * @return This builder for chaining.
     */
    public Builder setChain(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chain_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string chain = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChain() {
      
      chain_ = getDefaultInstance().getChain();
      onChanged();
      return this;
    }
    /**
     * <code>string chain = 1;</code>
     * @param value The bytes for chain to set.
     * @return This builder for chaining.
     */
    public Builder setChainBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chain_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object transactionHash_ = "";
    /**
     * <code>string transactionHash = 2;</code>
     * @return The transactionHash.
     */
    public java.lang.String getTransactionHash() {
      java.lang.Object ref = transactionHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transactionHash = 2;</code>
     * @return The bytes for transactionHash.
     */
    public com.google.protobuf.ByteString
        getTransactionHashBytes() {
      java.lang.Object ref = transactionHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transactionHash = 2;</code>
     * @param value The transactionHash to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transactionHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string transactionHash = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionHash() {
      
      transactionHash_ = getDefaultInstance().getTransactionHash();
      onChanged();
      return this;
    }
    /**
     * <code>string transactionHash = 2;</code>
     * @param value The bytes for transactionHash to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transactionHash_ = value;
      onChanged();
      return this;
    }

    private int transactionIndex_ ;
    /**
     * <code>int32 transactionIndex = 3;</code>
     * @return The transactionIndex.
     */
    @java.lang.Override
    public int getTransactionIndex() {
      return transactionIndex_;
    }
    /**
     * <code>int32 transactionIndex = 3;</code>
     * @param value The transactionIndex to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionIndex(int value) {
      
      transactionIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 transactionIndex = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionIndex() {
      
      transactionIndex_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object blockHash_ = "";
    /**
     * <code>string blockHash = 4;</code>
     * @return The blockHash.
     */
    public java.lang.String getBlockHash() {
      java.lang.Object ref = blockHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        blockHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string blockHash = 4;</code>
     * @return The bytes for blockHash.
     */
    public com.google.protobuf.ByteString
        getBlockHashBytes() {
      java.lang.Object ref = blockHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blockHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string blockHash = 4;</code>
     * @param value The blockHash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockHash(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      blockHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string blockHash = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockHash() {
      
      blockHash_ = getDefaultInstance().getBlockHash();
      onChanged();
      return this;
    }
    /**
     * <code>string blockHash = 4;</code>
     * @param value The bytes for blockHash to set.
     * @return This builder for chaining.
     */
    public Builder setBlockHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      blockHash_ = value;
      onChanged();
      return this;
    }

    private long blockNumber_ ;
    /**
     * <code>int64 blockNumber = 5;</code>
     * @return The blockNumber.
     */
    @java.lang.Override
    public long getBlockNumber() {
      return blockNumber_;
    }
    /**
     * <code>int64 blockNumber = 5;</code>
     * @param value The blockNumber to set.
     * @return This builder for chaining.
     */
    public Builder setBlockNumber(long value) {
      
      blockNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 blockNumber = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockNumber() {
      
      blockNumber_ = 0L;
      onChanged();
      return this;
    }

    private long gasUsed_ ;
    /**
     * <code>int64 gasUsed = 6;</code>
     * @return The gasUsed.
     */
    @java.lang.Override
    public long getGasUsed() {
      return gasUsed_;
    }
    /**
     * <code>int64 gasUsed = 6;</code>
     * @param value The gasUsed to set.
     * @return This builder for chaining.
     */
    public Builder setGasUsed(long value) {
      
      gasUsed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 gasUsed = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearGasUsed() {
      
      gasUsed_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object contractAddress_ = "";
    /**
     * <code>string contractAddress = 7;</code>
     * @return The contractAddress.
     */
    public java.lang.String getContractAddress() {
      java.lang.Object ref = contractAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contractAddress = 7;</code>
     * @return The bytes for contractAddress.
     */
    public com.google.protobuf.ByteString
        getContractAddressBytes() {
      java.lang.Object ref = contractAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contractAddress = 7;</code>
     * @param value The contractAddress to set.
     * @return This builder for chaining.
     */
    public Builder setContractAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contractAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contractAddress = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractAddress() {
      
      contractAddress_ = getDefaultInstance().getContractAddress();
      onChanged();
      return this;
    }
    /**
     * <code>string contractAddress = 7;</code>
     * @param value The bytes for contractAddress to set.
     * @return This builder for chaining.
     */
    public Builder setContractAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contractAddress_ = value;
      onChanged();
      return this;
    }

    private boolean transactionReceiptStatus_ ;
    /**
     * <code>bool transactionReceiptStatus = 8;</code>
     * @return The transactionReceiptStatus.
     */
    @java.lang.Override
    public boolean getTransactionReceiptStatus() {
      return transactionReceiptStatus_;
    }
    /**
     * <code>bool transactionReceiptStatus = 8;</code>
     * @param value The transactionReceiptStatus to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionReceiptStatus(boolean value) {
      
      transactionReceiptStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool transactionReceiptStatus = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionReceiptStatus() {
      
      transactionReceiptStatus_ = false;
      onChanged();
      return this;
    }

    private int eventCount_ ;
    /**
     * <code>int32 eventCount = 9;</code>
     * @return The eventCount.
     */
    @java.lang.Override
    public int getEventCount() {
      return eventCount_;
    }
    /**
     * <code>int32 eventCount = 9;</code>
     * @param value The eventCount to set.
     * @return This builder for chaining.
     */
    public Builder setEventCount(int value) {
      
      eventCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 eventCount = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventCount() {
      
      eventCount_ = 0;
      onChanged();
      return this;
    }

    private long blockTimestamp_ ;
    /**
     * <code>int64 blockTimestamp = 10;</code>
     * @return The blockTimestamp.
     */
    @java.lang.Override
    public long getBlockTimestamp() {
      return blockTimestamp_;
    }
    /**
     * <code>int64 blockTimestamp = 10;</code>
     * @param value The blockTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setBlockTimestamp(long value) {
      
      blockTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 blockTimestamp = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockTimestamp() {
      
      blockTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<io.eigenphi.erigon.protos.EventLog> eventLogs_ =
      java.util.Collections.emptyList();
    private void ensureEventLogsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        eventLogs_ = new java.util.ArrayList<io.eigenphi.erigon.protos.EventLog>(eventLogs_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.eigenphi.erigon.protos.EventLog, io.eigenphi.erigon.protos.EventLog.Builder, io.eigenphi.erigon.protos.EventLogOrBuilder> eventLogsBuilder_;

    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public java.util.List<io.eigenphi.erigon.protos.EventLog> getEventLogsList() {
      if (eventLogsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(eventLogs_);
      } else {
        return eventLogsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public int getEventLogsCount() {
      if (eventLogsBuilder_ == null) {
        return eventLogs_.size();
      } else {
        return eventLogsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public io.eigenphi.erigon.protos.EventLog getEventLogs(int index) {
      if (eventLogsBuilder_ == null) {
        return eventLogs_.get(index);
      } else {
        return eventLogsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public Builder setEventLogs(
        int index, io.eigenphi.erigon.protos.EventLog value) {
      if (eventLogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventLogsIsMutable();
        eventLogs_.set(index, value);
        onChanged();
      } else {
        eventLogsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public Builder setEventLogs(
        int index, io.eigenphi.erigon.protos.EventLog.Builder builderForValue) {
      if (eventLogsBuilder_ == null) {
        ensureEventLogsIsMutable();
        eventLogs_.set(index, builderForValue.build());
        onChanged();
      } else {
        eventLogsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public Builder addEventLogs(io.eigenphi.erigon.protos.EventLog value) {
      if (eventLogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventLogsIsMutable();
        eventLogs_.add(value);
        onChanged();
      } else {
        eventLogsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public Builder addEventLogs(
        int index, io.eigenphi.erigon.protos.EventLog value) {
      if (eventLogsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventLogsIsMutable();
        eventLogs_.add(index, value);
        onChanged();
      } else {
        eventLogsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public Builder addEventLogs(
        io.eigenphi.erigon.protos.EventLog.Builder builderForValue) {
      if (eventLogsBuilder_ == null) {
        ensureEventLogsIsMutable();
        eventLogs_.add(builderForValue.build());
        onChanged();
      } else {
        eventLogsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public Builder addEventLogs(
        int index, io.eigenphi.erigon.protos.EventLog.Builder builderForValue) {
      if (eventLogsBuilder_ == null) {
        ensureEventLogsIsMutable();
        eventLogs_.add(index, builderForValue.build());
        onChanged();
      } else {
        eventLogsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public Builder addAllEventLogs(
        java.lang.Iterable<? extends io.eigenphi.erigon.protos.EventLog> values) {
      if (eventLogsBuilder_ == null) {
        ensureEventLogsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, eventLogs_);
        onChanged();
      } else {
        eventLogsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public Builder clearEventLogs() {
      if (eventLogsBuilder_ == null) {
        eventLogs_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        eventLogsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public Builder removeEventLogs(int index) {
      if (eventLogsBuilder_ == null) {
        ensureEventLogsIsMutable();
        eventLogs_.remove(index);
        onChanged();
      } else {
        eventLogsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public io.eigenphi.erigon.protos.EventLog.Builder getEventLogsBuilder(
        int index) {
      return getEventLogsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public io.eigenphi.erigon.protos.EventLogOrBuilder getEventLogsOrBuilder(
        int index) {
      if (eventLogsBuilder_ == null) {
        return eventLogs_.get(index);  } else {
        return eventLogsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public java.util.List<? extends io.eigenphi.erigon.protos.EventLogOrBuilder> 
         getEventLogsOrBuilderList() {
      if (eventLogsBuilder_ != null) {
        return eventLogsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(eventLogs_);
      }
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public io.eigenphi.erigon.protos.EventLog.Builder addEventLogsBuilder() {
      return getEventLogsFieldBuilder().addBuilder(
          io.eigenphi.erigon.protos.EventLog.getDefaultInstance());
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public io.eigenphi.erigon.protos.EventLog.Builder addEventLogsBuilder(
        int index) {
      return getEventLogsFieldBuilder().addBuilder(
          index, io.eigenphi.erigon.protos.EventLog.getDefaultInstance());
    }
    /**
     * <code>repeated .erigon.EventLog eventLogs = 11;</code>
     */
    public java.util.List<io.eigenphi.erigon.protos.EventLog.Builder> 
         getEventLogsBuilderList() {
      return getEventLogsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.eigenphi.erigon.protos.EventLog, io.eigenphi.erigon.protos.EventLog.Builder, io.eigenphi.erigon.protos.EventLogOrBuilder> 
        getEventLogsFieldBuilder() {
      if (eventLogsBuilder_ == null) {
        eventLogsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.eigenphi.erigon.protos.EventLog, io.eigenphi.erigon.protos.EventLog.Builder, io.eigenphi.erigon.protos.EventLogOrBuilder>(
                eventLogs_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        eventLogs_ = null;
      }
      return eventLogsBuilder_;
    }

    private java.lang.Object senderInfo_ = "";
    /**
     * <code>string senderInfo = 12;</code>
     * @return The senderInfo.
     */
    public java.lang.String getSenderInfo() {
      java.lang.Object ref = senderInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string senderInfo = 12;</code>
     * @return The bytes for senderInfo.
     */
    public com.google.protobuf.ByteString
        getSenderInfoBytes() {
      java.lang.Object ref = senderInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string senderInfo = 12;</code>
     * @param value The senderInfo to set.
     * @return This builder for chaining.
     */
    public Builder setSenderInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string senderInfo = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderInfo() {
      
      senderInfo_ = getDefaultInstance().getSenderInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string senderInfo = 12;</code>
     * @param value The bytes for senderInfo to set.
     * @return This builder for chaining.
     */
    public Builder setSenderInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderInfo_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:erigon.Receipt)
  }

  // @@protoc_insertion_point(class_scope:erigon.Receipt)
  private static final io.eigenphi.erigon.protos.Receipt DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.eigenphi.erigon.protos.Receipt();
  }

  public static io.eigenphi.erigon.protos.Receipt getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Receipt>
      PARSER = new com.google.protobuf.AbstractParser<Receipt>() {
    @java.lang.Override
    public Receipt parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Receipt> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Receipt> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.eigenphi.erigon.protos.Receipt getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

