// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Block.proto

package io.eigenphi.erigon.protos;

public interface ReceiptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:erigon.Receipt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string chain = 1;</code>
   * @return The chain.
   */
  java.lang.String getChain();
  /**
   * <code>string chain = 1;</code>
   * @return The bytes for chain.
   */
  com.google.protobuf.ByteString
      getChainBytes();

  /**
   * <code>string transactionHash = 2;</code>
   * @return The transactionHash.
   */
  java.lang.String getTransactionHash();
  /**
   * <code>string transactionHash = 2;</code>
   * @return The bytes for transactionHash.
   */
  com.google.protobuf.ByteString
      getTransactionHashBytes();

  /**
   * <code>int32 transactionIndex = 3;</code>
   * @return The transactionIndex.
   */
  int getTransactionIndex();

  /**
   * <code>string blockHash = 4;</code>
   * @return The blockHash.
   */
  java.lang.String getBlockHash();
  /**
   * <code>string blockHash = 4;</code>
   * @return The bytes for blockHash.
   */
  com.google.protobuf.ByteString
      getBlockHashBytes();

  /**
   * <code>int64 blockNumber = 5;</code>
   * @return The blockNumber.
   */
  long getBlockNumber();

  /**
   * <code>int64 gasUsed = 6;</code>
   * @return The gasUsed.
   */
  long getGasUsed();

  /**
   * <code>string contractAddress = 7;</code>
   * @return The contractAddress.
   */
  java.lang.String getContractAddress();
  /**
   * <code>string contractAddress = 7;</code>
   * @return The bytes for contractAddress.
   */
  com.google.protobuf.ByteString
      getContractAddressBytes();

  /**
   * <code>bool transactionReceiptStatus = 8;</code>
   * @return The transactionReceiptStatus.
   */
  boolean getTransactionReceiptStatus();

  /**
   * <code>int32 eventCount = 9;</code>
   * @return The eventCount.
   */
  int getEventCount();

  /**
   * <code>int64 blockTimestamp = 10;</code>
   * @return The blockTimestamp.
   */
  long getBlockTimestamp();

  /**
   * <code>repeated .erigon.EventLog eventLogs = 11;</code>
   */
  java.util.List<io.eigenphi.erigon.protos.EventLog> 
      getEventLogsList();
  /**
   * <code>repeated .erigon.EventLog eventLogs = 11;</code>
   */
  io.eigenphi.erigon.protos.EventLog getEventLogs(int index);
  /**
   * <code>repeated .erigon.EventLog eventLogs = 11;</code>
   */
  int getEventLogsCount();
  /**
   * <code>repeated .erigon.EventLog eventLogs = 11;</code>
   */
  java.util.List<? extends io.eigenphi.erigon.protos.EventLogOrBuilder> 
      getEventLogsOrBuilderList();
  /**
   * <code>repeated .erigon.EventLog eventLogs = 11;</code>
   */
  io.eigenphi.erigon.protos.EventLogOrBuilder getEventLogsOrBuilder(
      int index);

  /**
   * <code>string senderInfo = 12;</code>
   * @return The senderInfo.
   */
  java.lang.String getSenderInfo();
  /**
   * <code>string senderInfo = 12;</code>
   * @return The bytes for senderInfo.
   */
  com.google.protobuf.ByteString
      getSenderInfoBytes();
}
