// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Block.proto

package io.eigenphi.erigon.protos;

/**
 * Protobuf type {@code erigon.stackFrame}
 */
public final class stackFrame extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:erigon.stackFrame)
    stackFrameOrBuilder {
private static final long serialVersionUID = 0L;
  // Use stackFrame.newBuilder() to construct.
  private stackFrame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private stackFrame() {
    type_ = "";
    label_ = "";
    from_ = "";
    to_ = "";
    contractCreated_ = "";
    value_ = "";
    input_ = "";
    error_ = "";
    calls_ = java.util.Collections.emptyList();
    fourBytes_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new stackFrame();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_stackFrame_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_stackFrame_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.eigenphi.erigon.protos.stackFrame.class, io.eigenphi.erigon.protos.stackFrame.Builder.class);
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object type_;
  /**
   * <pre>
   * OP code
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * OP code
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LABEL_FIELD_NUMBER = 2;
  private volatile java.lang.Object label_;
  /**
   * <pre>
   * empty or "Transfer" or "Internal-Transfer"
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The label.
   */
  @java.lang.Override
  public java.lang.String getLabel() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      label_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * empty or "Transfer" or "Internal-Transfer"
   * </pre>
   *
   * <code>string label = 2;</code>
   * @return The bytes for label.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelBytes() {
    java.lang.Object ref = label_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      label_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROM_FIELD_NUMBER = 3;
  private volatile java.lang.Object from_;
  /**
   * <code>string from = 3;</code>
   * @return The from.
   */
  @java.lang.Override
  public java.lang.String getFrom() {
    java.lang.Object ref = from_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      from_ = s;
      return s;
    }
  }
  /**
   * <code>string from = 3;</code>
   * @return The bytes for from.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromBytes() {
    java.lang.Object ref = from_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      from_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TO_FIELD_NUMBER = 4;
  private volatile java.lang.Object to_;
  /**
   * <code>string to = 4;</code>
   * @return The to.
   */
  @java.lang.Override
  public java.lang.String getTo() {
    java.lang.Object ref = to_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      to_ = s;
      return s;
    }
  }
  /**
   * <code>string to = 4;</code>
   * @return The bytes for to.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToBytes() {
    java.lang.Object ref = to_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      to_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTRACTCREATED_FIELD_NUMBER = 5;
  private volatile java.lang.Object contractCreated_;
  /**
   * <code>string contractCreated = 5;</code>
   * @return The contractCreated.
   */
  @java.lang.Override
  public java.lang.String getContractCreated() {
    java.lang.Object ref = contractCreated_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contractCreated_ = s;
      return s;
    }
  }
  /**
   * <code>string contractCreated = 5;</code>
   * @return The bytes for contractCreated.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContractCreatedBytes() {
    java.lang.Object ref = contractCreated_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contractCreated_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 6;
  private volatile java.lang.Object value_;
  /**
   * <code>string value = 6;</code>
   * @return The value.
   */
  @java.lang.Override
  public java.lang.String getValue() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      value_ = s;
      return s;
    }
  }
  /**
   * <code>string value = 6;</code>
   * @return The bytes for value.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getValueBytes() {
    java.lang.Object ref = value_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      value_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INPUT_FIELD_NUMBER = 7;
  private volatile java.lang.Object input_;
  /**
   * <code>string input = 7;</code>
   * @return The input.
   */
  @java.lang.Override
  public java.lang.String getInput() {
    java.lang.Object ref = input_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      input_ = s;
      return s;
    }
  }
  /**
   * <code>string input = 7;</code>
   * @return The bytes for input.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInputBytes() {
    java.lang.Object ref = input_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      input_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERROR_FIELD_NUMBER = 8;
  private volatile java.lang.Object error_;
  /**
   * <code>string error = 8;</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <code>string error = 8;</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CALLS_FIELD_NUMBER = 9;
  private java.util.List<io.eigenphi.erigon.protos.stackFrame> calls_;
  /**
   * <code>repeated .erigon.stackFrame calls = 9;</code>
   */
  @java.lang.Override
  public java.util.List<io.eigenphi.erigon.protos.stackFrame> getCallsList() {
    return calls_;
  }
  /**
   * <code>repeated .erigon.stackFrame calls = 9;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.eigenphi.erigon.protos.stackFrameOrBuilder> 
      getCallsOrBuilderList() {
    return calls_;
  }
  /**
   * <code>repeated .erigon.stackFrame calls = 9;</code>
   */
  @java.lang.Override
  public int getCallsCount() {
    return calls_.size();
  }
  /**
   * <code>repeated .erigon.stackFrame calls = 9;</code>
   */
  @java.lang.Override
  public io.eigenphi.erigon.protos.stackFrame getCalls(int index) {
    return calls_.get(index);
  }
  /**
   * <code>repeated .erigon.stackFrame calls = 9;</code>
   */
  @java.lang.Override
  public io.eigenphi.erigon.protos.stackFrameOrBuilder getCallsOrBuilder(
      int index) {
    return calls_.get(index);
  }

  public static final int FOURBYTES_FIELD_NUMBER = 10;
  private volatile java.lang.Object fourBytes_;
  /**
   * <code>string fourBytes = 10;</code>
   * @return The fourBytes.
   */
  @java.lang.Override
  public java.lang.String getFourBytes() {
    java.lang.Object ref = fourBytes_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fourBytes_ = s;
      return s;
    }
  }
  /**
   * <code>string fourBytes = 10;</code>
   * @return The bytes for fourBytes.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFourBytesBytes() {
    java.lang.Object ref = fourBytes_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fourBytes_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(label_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, label_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(from_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, from_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(to_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, to_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractCreated_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, contractCreated_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, value_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(input_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, input_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, error_);
    }
    for (int i = 0; i < calls_.size(); i++) {
      output.writeMessage(9, calls_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fourBytes_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, fourBytes_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(label_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, label_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(from_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, from_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(to_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, to_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contractCreated_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, contractCreated_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, value_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(input_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, input_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, error_);
    }
    for (int i = 0; i < calls_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, calls_.get(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fourBytes_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, fourBytes_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.eigenphi.erigon.protos.stackFrame)) {
      return super.equals(obj);
    }
    io.eigenphi.erigon.protos.stackFrame other = (io.eigenphi.erigon.protos.stackFrame) obj;

    if (!getType()
        .equals(other.getType())) return false;
    if (!getLabel()
        .equals(other.getLabel())) return false;
    if (!getFrom()
        .equals(other.getFrom())) return false;
    if (!getTo()
        .equals(other.getTo())) return false;
    if (!getContractCreated()
        .equals(other.getContractCreated())) return false;
    if (!getValue()
        .equals(other.getValue())) return false;
    if (!getInput()
        .equals(other.getInput())) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (!getCallsList()
        .equals(other.getCallsList())) return false;
    if (!getFourBytes()
        .equals(other.getFourBytes())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + LABEL_FIELD_NUMBER;
    hash = (53 * hash) + getLabel().hashCode();
    hash = (37 * hash) + FROM_FIELD_NUMBER;
    hash = (53 * hash) + getFrom().hashCode();
    hash = (37 * hash) + TO_FIELD_NUMBER;
    hash = (53 * hash) + getTo().hashCode();
    hash = (37 * hash) + CONTRACTCREATED_FIELD_NUMBER;
    hash = (53 * hash) + getContractCreated().hashCode();
    hash = (37 * hash) + VALUE_FIELD_NUMBER;
    hash = (53 * hash) + getValue().hashCode();
    hash = (37 * hash) + INPUT_FIELD_NUMBER;
    hash = (53 * hash) + getInput().hashCode();
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    if (getCallsCount() > 0) {
      hash = (37 * hash) + CALLS_FIELD_NUMBER;
      hash = (53 * hash) + getCallsList().hashCode();
    }
    hash = (37 * hash) + FOURBYTES_FIELD_NUMBER;
    hash = (53 * hash) + getFourBytes().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.eigenphi.erigon.protos.stackFrame parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.eigenphi.erigon.protos.stackFrame parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.stackFrame parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.eigenphi.erigon.protos.stackFrame parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.stackFrame parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.eigenphi.erigon.protos.stackFrame parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.stackFrame parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.eigenphi.erigon.protos.stackFrame parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.stackFrame parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.eigenphi.erigon.protos.stackFrame parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.eigenphi.erigon.protos.stackFrame parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.eigenphi.erigon.protos.stackFrame parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.eigenphi.erigon.protos.stackFrame prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code erigon.stackFrame}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:erigon.stackFrame)
      io.eigenphi.erigon.protos.stackFrameOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_stackFrame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_stackFrame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.eigenphi.erigon.protos.stackFrame.class, io.eigenphi.erigon.protos.stackFrame.Builder.class);
    }

    // Construct using io.eigenphi.erigon.protos.stackFrame.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      type_ = "";

      label_ = "";

      from_ = "";

      to_ = "";

      contractCreated_ = "";

      value_ = "";

      input_ = "";

      error_ = "";

      if (callsBuilder_ == null) {
        calls_ = java.util.Collections.emptyList();
      } else {
        calls_ = null;
        callsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      fourBytes_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.eigenphi.erigon.protos.ErigonProtos.internal_static_erigon_stackFrame_descriptor;
    }

    @java.lang.Override
    public io.eigenphi.erigon.protos.stackFrame getDefaultInstanceForType() {
      return io.eigenphi.erigon.protos.stackFrame.getDefaultInstance();
    }

    @java.lang.Override
    public io.eigenphi.erigon.protos.stackFrame build() {
      io.eigenphi.erigon.protos.stackFrame result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.eigenphi.erigon.protos.stackFrame buildPartial() {
      io.eigenphi.erigon.protos.stackFrame result = new io.eigenphi.erigon.protos.stackFrame(this);
      int from_bitField0_ = bitField0_;
      result.type_ = type_;
      result.label_ = label_;
      result.from_ = from_;
      result.to_ = to_;
      result.contractCreated_ = contractCreated_;
      result.value_ = value_;
      result.input_ = input_;
      result.error_ = error_;
      if (callsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          calls_ = java.util.Collections.unmodifiableList(calls_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.calls_ = calls_;
      } else {
        result.calls_ = callsBuilder_.build();
      }
      result.fourBytes_ = fourBytes_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.eigenphi.erigon.protos.stackFrame) {
        return mergeFrom((io.eigenphi.erigon.protos.stackFrame)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.eigenphi.erigon.protos.stackFrame other) {
      if (other == io.eigenphi.erigon.protos.stackFrame.getDefaultInstance()) return this;
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.getLabel().isEmpty()) {
        label_ = other.label_;
        onChanged();
      }
      if (!other.getFrom().isEmpty()) {
        from_ = other.from_;
        onChanged();
      }
      if (!other.getTo().isEmpty()) {
        to_ = other.to_;
        onChanged();
      }
      if (!other.getContractCreated().isEmpty()) {
        contractCreated_ = other.contractCreated_;
        onChanged();
      }
      if (!other.getValue().isEmpty()) {
        value_ = other.value_;
        onChanged();
      }
      if (!other.getInput().isEmpty()) {
        input_ = other.input_;
        onChanged();
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        onChanged();
      }
      if (callsBuilder_ == null) {
        if (!other.calls_.isEmpty()) {
          if (calls_.isEmpty()) {
            calls_ = other.calls_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCallsIsMutable();
            calls_.addAll(other.calls_);
          }
          onChanged();
        }
      } else {
        if (!other.calls_.isEmpty()) {
          if (callsBuilder_.isEmpty()) {
            callsBuilder_.dispose();
            callsBuilder_ = null;
            calls_ = other.calls_;
            bitField0_ = (bitField0_ & ~0x00000001);
            callsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCallsFieldBuilder() : null;
          } else {
            callsBuilder_.addAllMessages(other.calls_);
          }
        }
      }
      if (!other.getFourBytes().isEmpty()) {
        fourBytes_ = other.fourBytes_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              type_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              label_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              from_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              to_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              contractCreated_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              value_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 58: {
              input_ = input.readStringRequireUtf8();

              break;
            } // case 58
            case 66: {
              error_ = input.readStringRequireUtf8();

              break;
            } // case 66
            case 74: {
              io.eigenphi.erigon.protos.stackFrame m =
                  input.readMessage(
                      io.eigenphi.erigon.protos.stackFrame.parser(),
                      extensionRegistry);
              if (callsBuilder_ == null) {
                ensureCallsIsMutable();
                calls_.add(m);
              } else {
                callsBuilder_.addMessage(m);
              }
              break;
            } // case 74
            case 82: {
              fourBytes_ = input.readStringRequireUtf8();

              break;
            } // case 82
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object type_ = "";
    /**
     * <pre>
     * OP code
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * OP code
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * OP code
     * </pre>
     *
     * <code>string type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * OP code
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * OP code
     * </pre>
     *
     * <code>string type = 1;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object label_ = "";
    /**
     * <pre>
     * empty or "Transfer" or "Internal-Transfer"
     * </pre>
     *
     * <code>string label = 2;</code>
     * @return The label.
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * empty or "Transfer" or "Internal-Transfer"
     * </pre>
     *
     * <code>string label = 2;</code>
     * @return The bytes for label.
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * empty or "Transfer" or "Internal-Transfer"
     * </pre>
     *
     * <code>string label = 2;</code>
     * @param value The label to set.
     * @return This builder for chaining.
     */
    public Builder setLabel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      label_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * empty or "Transfer" or "Internal-Transfer"
     * </pre>
     *
     * <code>string label = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLabel() {
      
      label_ = getDefaultInstance().getLabel();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * empty or "Transfer" or "Internal-Transfer"
     * </pre>
     *
     * <code>string label = 2;</code>
     * @param value The bytes for label to set.
     * @return This builder for chaining.
     */
    public Builder setLabelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      label_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object from_ = "";
    /**
     * <code>string from = 3;</code>
     * @return The from.
     */
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        from_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string from = 3;</code>
     * @return The bytes for from.
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string from = 3;</code>
     * @param value The from to set.
     * @return This builder for chaining.
     */
    public Builder setFrom(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      from_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string from = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrom() {
      
      from_ = getDefaultInstance().getFrom();
      onChanged();
      return this;
    }
    /**
     * <code>string from = 3;</code>
     * @param value The bytes for from to set.
     * @return This builder for chaining.
     */
    public Builder setFromBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      from_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object to_ = "";
    /**
     * <code>string to = 4;</code>
     * @return The to.
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string to = 4;</code>
     * @return The bytes for to.
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string to = 4;</code>
     * @param value The to to set.
     * @return This builder for chaining.
     */
    public Builder setTo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      to_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string to = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTo() {
      
      to_ = getDefaultInstance().getTo();
      onChanged();
      return this;
    }
    /**
     * <code>string to = 4;</code>
     * @param value The bytes for to to set.
     * @return This builder for chaining.
     */
    public Builder setToBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      to_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object contractCreated_ = "";
    /**
     * <code>string contractCreated = 5;</code>
     * @return The contractCreated.
     */
    public java.lang.String getContractCreated() {
      java.lang.Object ref = contractCreated_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contractCreated_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string contractCreated = 5;</code>
     * @return The bytes for contractCreated.
     */
    public com.google.protobuf.ByteString
        getContractCreatedBytes() {
      java.lang.Object ref = contractCreated_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contractCreated_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string contractCreated = 5;</code>
     * @param value The contractCreated to set.
     * @return This builder for chaining.
     */
    public Builder setContractCreated(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contractCreated_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string contractCreated = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearContractCreated() {
      
      contractCreated_ = getDefaultInstance().getContractCreated();
      onChanged();
      return this;
    }
    /**
     * <code>string contractCreated = 5;</code>
     * @param value The bytes for contractCreated to set.
     * @return This builder for chaining.
     */
    public Builder setContractCreatedBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contractCreated_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object value_ = "";
    /**
     * <code>string value = 6;</code>
     * @return The value.
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string value = 6;</code>
     * @return The bytes for value.
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string value = 6;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      value_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string value = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      
      value_ = getDefaultInstance().getValue();
      onChanged();
      return this;
    }
    /**
     * <code>string value = 6;</code>
     * @param value The bytes for value to set.
     * @return This builder for chaining.
     */
    public Builder setValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      value_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object input_ = "";
    /**
     * <code>string input = 7;</code>
     * @return The input.
     */
    public java.lang.String getInput() {
      java.lang.Object ref = input_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        input_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string input = 7;</code>
     * @return The bytes for input.
     */
    public com.google.protobuf.ByteString
        getInputBytes() {
      java.lang.Object ref = input_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        input_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string input = 7;</code>
     * @param value The input to set.
     * @return This builder for chaining.
     */
    public Builder setInput(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      input_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string input = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearInput() {
      
      input_ = getDefaultInstance().getInput();
      onChanged();
      return this;
    }
    /**
     * <code>string input = 7;</code>
     * @param value The bytes for input to set.
     * @return This builder for chaining.
     */
    public Builder setInputBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      input_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object error_ = "";
    /**
     * <code>string error = 8;</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string error = 8;</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string error = 8;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      error_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string error = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      
      error_ = getDefaultInstance().getError();
      onChanged();
      return this;
    }
    /**
     * <code>string error = 8;</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      error_ = value;
      onChanged();
      return this;
    }

    private java.util.List<io.eigenphi.erigon.protos.stackFrame> calls_ =
      java.util.Collections.emptyList();
    private void ensureCallsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        calls_ = new java.util.ArrayList<io.eigenphi.erigon.protos.stackFrame>(calls_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.eigenphi.erigon.protos.stackFrame, io.eigenphi.erigon.protos.stackFrame.Builder, io.eigenphi.erigon.protos.stackFrameOrBuilder> callsBuilder_;

    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public java.util.List<io.eigenphi.erigon.protos.stackFrame> getCallsList() {
      if (callsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(calls_);
      } else {
        return callsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public int getCallsCount() {
      if (callsBuilder_ == null) {
        return calls_.size();
      } else {
        return callsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public io.eigenphi.erigon.protos.stackFrame getCalls(int index) {
      if (callsBuilder_ == null) {
        return calls_.get(index);
      } else {
        return callsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public Builder setCalls(
        int index, io.eigenphi.erigon.protos.stackFrame value) {
      if (callsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCallsIsMutable();
        calls_.set(index, value);
        onChanged();
      } else {
        callsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public Builder setCalls(
        int index, io.eigenphi.erigon.protos.stackFrame.Builder builderForValue) {
      if (callsBuilder_ == null) {
        ensureCallsIsMutable();
        calls_.set(index, builderForValue.build());
        onChanged();
      } else {
        callsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public Builder addCalls(io.eigenphi.erigon.protos.stackFrame value) {
      if (callsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCallsIsMutable();
        calls_.add(value);
        onChanged();
      } else {
        callsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public Builder addCalls(
        int index, io.eigenphi.erigon.protos.stackFrame value) {
      if (callsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCallsIsMutable();
        calls_.add(index, value);
        onChanged();
      } else {
        callsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public Builder addCalls(
        io.eigenphi.erigon.protos.stackFrame.Builder builderForValue) {
      if (callsBuilder_ == null) {
        ensureCallsIsMutable();
        calls_.add(builderForValue.build());
        onChanged();
      } else {
        callsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public Builder addCalls(
        int index, io.eigenphi.erigon.protos.stackFrame.Builder builderForValue) {
      if (callsBuilder_ == null) {
        ensureCallsIsMutable();
        calls_.add(index, builderForValue.build());
        onChanged();
      } else {
        callsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public Builder addAllCalls(
        java.lang.Iterable<? extends io.eigenphi.erigon.protos.stackFrame> values) {
      if (callsBuilder_ == null) {
        ensureCallsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, calls_);
        onChanged();
      } else {
        callsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public Builder clearCalls() {
      if (callsBuilder_ == null) {
        calls_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        callsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public Builder removeCalls(int index) {
      if (callsBuilder_ == null) {
        ensureCallsIsMutable();
        calls_.remove(index);
        onChanged();
      } else {
        callsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public io.eigenphi.erigon.protos.stackFrame.Builder getCallsBuilder(
        int index) {
      return getCallsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public io.eigenphi.erigon.protos.stackFrameOrBuilder getCallsOrBuilder(
        int index) {
      if (callsBuilder_ == null) {
        return calls_.get(index);  } else {
        return callsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public java.util.List<? extends io.eigenphi.erigon.protos.stackFrameOrBuilder> 
         getCallsOrBuilderList() {
      if (callsBuilder_ != null) {
        return callsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(calls_);
      }
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public io.eigenphi.erigon.protos.stackFrame.Builder addCallsBuilder() {
      return getCallsFieldBuilder().addBuilder(
          io.eigenphi.erigon.protos.stackFrame.getDefaultInstance());
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public io.eigenphi.erigon.protos.stackFrame.Builder addCallsBuilder(
        int index) {
      return getCallsFieldBuilder().addBuilder(
          index, io.eigenphi.erigon.protos.stackFrame.getDefaultInstance());
    }
    /**
     * <code>repeated .erigon.stackFrame calls = 9;</code>
     */
    public java.util.List<io.eigenphi.erigon.protos.stackFrame.Builder> 
         getCallsBuilderList() {
      return getCallsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.eigenphi.erigon.protos.stackFrame, io.eigenphi.erigon.protos.stackFrame.Builder, io.eigenphi.erigon.protos.stackFrameOrBuilder> 
        getCallsFieldBuilder() {
      if (callsBuilder_ == null) {
        callsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.eigenphi.erigon.protos.stackFrame, io.eigenphi.erigon.protos.stackFrame.Builder, io.eigenphi.erigon.protos.stackFrameOrBuilder>(
                calls_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        calls_ = null;
      }
      return callsBuilder_;
    }

    private java.lang.Object fourBytes_ = "";
    /**
     * <code>string fourBytes = 10;</code>
     * @return The fourBytes.
     */
    public java.lang.String getFourBytes() {
      java.lang.Object ref = fourBytes_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fourBytes_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fourBytes = 10;</code>
     * @return The bytes for fourBytes.
     */
    public com.google.protobuf.ByteString
        getFourBytesBytes() {
      java.lang.Object ref = fourBytes_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fourBytes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fourBytes = 10;</code>
     * @param value The fourBytes to set.
     * @return This builder for chaining.
     */
    public Builder setFourBytes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fourBytes_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fourBytes = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearFourBytes() {
      
      fourBytes_ = getDefaultInstance().getFourBytes();
      onChanged();
      return this;
    }
    /**
     * <code>string fourBytes = 10;</code>
     * @param value The bytes for fourBytes to set.
     * @return This builder for chaining.
     */
    public Builder setFourBytesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fourBytes_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:erigon.stackFrame)
  }

  // @@protoc_insertion_point(class_scope:erigon.stackFrame)
  private static final io.eigenphi.erigon.protos.stackFrame DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.eigenphi.erigon.protos.stackFrame();
  }

  public static io.eigenphi.erigon.protos.stackFrame getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<stackFrame>
      PARSER = new com.google.protobuf.AbstractParser<stackFrame>() {
    @java.lang.Override
    public stackFrame parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<stackFrame> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<stackFrame> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.eigenphi.erigon.protos.stackFrame getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

