// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Block.proto

package io.eigenphi.erigon.protos;

public interface TransactionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:erigon.Transaction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transactionHash = 1;</code>
   * @return The transactionHash.
   */
  java.lang.String getTransactionHash();
  /**
   * <code>string transactionHash = 1;</code>
   * @return The bytes for transactionHash.
   */
  com.google.protobuf.ByteString
      getTransactionHashBytes();

  /**
   * <code>int32 transactionIndex = 2;</code>
   * @return The transactionIndex.
   */
  int getTransactionIndex();

  /**
   * <code>int64 blockNumber = 3;</code>
   * @return The blockNumber.
   */
  long getBlockNumber();

  /**
   * <code>string fromAddress = 4;</code>
   * @return The fromAddress.
   */
  java.lang.String getFromAddress();
  /**
   * <code>string fromAddress = 4;</code>
   * @return The bytes for fromAddress.
   */
  com.google.protobuf.ByteString
      getFromAddressBytes();

  /**
   * <code>string toAddress = 5;</code>
   * @return The toAddress.
   */
  java.lang.String getToAddress();
  /**
   * <code>string toAddress = 5;</code>
   * @return The bytes for toAddress.
   */
  com.google.protobuf.ByteString
      getToAddressBytes();

  /**
   * <code>int64 nonce = 6;</code>
   * @return The nonce.
   */
  long getNonce();

  /**
   * <code>string transactionValue = 7;</code>
   * @return The transactionValue.
   */
  java.lang.String getTransactionValue();
  /**
   * <code>string transactionValue = 7;</code>
   * @return The bytes for transactionValue.
   */
  com.google.protobuf.ByteString
      getTransactionValueBytes();

  /**
   * <code>int64 blockTimestamp = 8;</code>
   * @return The blockTimestamp.
   */
  long getBlockTimestamp();
}
